/* eslint-disable react-refresh/only-export-components -- provider and hook intentionally share one preference boundary. */
import {
  cloneElement,
  createContext,
  isValidElement,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Locale = "id" | "en";
export type Theme = "light" | "dark";

const LOCALE_KEY = "edusmart.locale";
const THEME_KEY = "edusmart.theme";

const messages = {
  id: {
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.retry": "Coba lagi",
    "common.settings": "Pengaturan",
    "common.signOut": "Keluar",
    "common.light": "Terang",
    "common.dark": "Gelap",
    "common.language": "Bahasa",
    "common.appearance": "Tampilan",
    "common.loading": "Memuat…",
    "common.previous": "Sebelumnya",
    "common.next": "Berikutnya",
    "common.page": "Halaman",
    "common.records": "data",
    "admissions.applicationCount": "{count} hasil terbatas pada gelombang yang dipilih.",
    "common.loadError": "Data tidak dapat dimuat",
    "common.loadErrorDescription":
      "Silakan coba lagi. Jika masalah berlanjut, hubungi administrator sekolah.",
    "common.saving": "Menyimpan…",
    "common.accessDenied": "Anda tidak memiliki akses ke bagian ini",
    "common.accessDeniedDescription":
      "Akses diperlukan di ruang kerja aktif untuk melihat data ini.",
    "common.selectOrganization": "Pilih organisasi terlebih dahulu",
    "common.selectOrganizationDescription": "Pilih organisasi pada bilah atas untuk melanjutkan.",
    "common.selectSchoolFirst": "Pilih sekolah terlebih dahulu",
    "academic.selectSchoolDescription":
      "Data akademik mengikuti sekolah yang dipilih. Pilih sekolah pada bilah atas untuk melanjutkan.",
    "common.status.active": "Aktif",
    "common.status.inactive": "Tidak aktif",
    "common.status.draft": "Draf",
    "common.status.published": "Diterbitkan",
    "common.status.submitted": "Diajukan",
    "common.status.accepted": "Diterima",
    "common.status.rejected": "Ditolak",
    "common.status.withdrawn": "Ditarik",
    "common.status.open": "Terbuka",
    "common.status.closed": "Ditutup",
    "common.status.archived": "Diarsipkan",
    "common.status.issued": "Diterbitkan",
    "common.status.paid": "Lunas",
    "common.status.unpaid": "Belum dibayar",
    "common.status.overdue": "Jatuh tempo",
    "common.status.void": "Dibatalkan",
    "common.status.cancelled": "Dibatalkan",
    "common.status.expired": "Kedaluwarsa",
    "common.status.missing": "Belum diisi",
    "common.status.excused": "Dikecualikan",
    "common.status.final": "Final",
    "common.noOrganization": "Tidak ada organisasi",
    "common.selectSchool": "Pilih sekolah",
    "common.academicYear": "Tahun ajaran",
    "common.term": "Semester",
    "common.noAcademicYear": "Tidak ada tahun ajaran",
    "common.noTerm": "Tidak ada semester",
    "common.account": "Akun",
    "common.version": "Versi",
    "common.openNavigation": "Buka navigasi",
    "common.closeNavigation": "Tutup navigasi",
    "common.dismissNavigationOverlay": "Tutup menu navigasi",
    "common.navigationMenu": "Menu navigasi",
    "common.workspace": "Ruang kerja",
    "navigation.dashboard": "Dasbor",
    "navigation.notifications": "Notifikasi",
    "navigation.permissionRequests": "Permintaan izin",
    "permissionRequests.activeSchool": "sekolah aktif",
    "permissionRequests.staffDescription": "Alur kerja staf untuk {school}.",
    "permissionRequests.serverPage": "Halaman server {page}",
    "navigation.communication": "Pusat komunikasi",
    "navigation.academicSetup": "Pengaturan akademik",
    "navigation.academicOperations": "Operasional akademik",
    "navigation.students": "Siswa",
    "navigation.studentInformation": "Data siswa",
    "navigation.admissions": "Penerimaan siswa",
    "navigation.finance": "Keuangan",
    "navigation.schoolOperations": "Operasional sekolah",
    "navigation.pilotReadiness": "Kesiapan pilot",
    "pilotReadiness.title": "Kesiapan pilot sekolah",
    "pilotReadiness.description":
      "Ringkasan read-only untuk memeriksa kesiapan alur pilot yang disepakati. Data dihitung dari kondisi sekolah saat ini.",
    "pilotReadiness.overall": "Ringkasan kesiapan",
    "pilotReadiness.overallExplanation":
      "Status ditentukan oleh pemeriksaan dengan tingkat risiko tertinggi.",
    "pilotReadiness.domains": "Pemeriksaan per domain",
    "pilotReadiness.refresh": "Perbarui pemeriksaan",
    "pilotReadiness.reviewLink": "Tinjau pengaturan",
    "pilotReadiness.count": "Jumlah: {count}",
    "pilotReadiness.generatedAt": "Dihitung pada {date}",
    "pilotReadiness.error":
      "Kesiapan tidak dapat dimuat. Coba lagi atau hubungi administrator sekolah.",
    "pilotReadiness.denied": "Anda tidak memiliki akses untuk melihat ringkasan kesiapan sekolah.",
    "pilotReadiness.syntheticDisclaimer":
      "Hasil teknis ini bukan persetujuan atau penerimaan pilot oleh sekolah. Konfirmasi alur dan penanggung jawab bersama pihak sekolah.",
    "pilotReadiness.status.READY": "Siap",
    "pilotReadiness.status.WARNING": "Perlu ditinjau",
    "pilotReadiness.status.BLOCKER": "Penghambat",
    "pilotReadiness.status.MANUAL_FALLBACK": "Alur manual",
    "pilotReadiness.domain.school": "Sekolah",
    "pilotReadiness.domain.academic_sis": "Akademik dan data siswa",
    "pilotReadiness.domain.teaching": "Operasional guru",
    "pilotReadiness.domain.portals": "Portal siswa dan orang tua",
    "pilotReadiness.domain.admissions": "Penerimaan siswa",
    "pilotReadiness.domain.finance": "Keuangan",
    "pilotReadiness.domain.communication": "Komunikasi",
    "pilotReadiness.check.SCHOOL_ACTIVE": "Status sekolah",
    "pilotReadiness.check.ACADEMIC_ACCESS": "Akses konfigurasi akademik",
    "pilotReadiness.check.ACTIVE_ACADEMIC_YEAR": "Tahun ajaran aktif",
    "pilotReadiness.check.ACTIVE_TERM": "Periode akademik aktif",
    "pilotReadiness.check.ACTIVE_CLASSROOMS": "Rombel aktif",
    "pilotReadiness.check.ACTIVE_ENROLLMENTS": "Pendaftaran siswa aktif",
    "pilotReadiness.check.CLASSROOM_ASSIGNMENT_COVERAGE": "Penempatan siswa ke rombel",
    "pilotReadiness.check.TEACHING_ACCESS": "Akses penugasan guru",
    "pilotReadiness.check.ACTIVE_TEACHER_ASSIGNMENTS": "Penugasan guru aktif",
    "pilotReadiness.check.STUDENT_PORTAL_ACCESS": "Akses data siswa untuk portal",
    "pilotReadiness.check.STUDENT_ACCOUNT_LINKS": "Akun siswa tertaut pada pendaftaran aktif",
    "pilotReadiness.check.GUARDIAN_LINK_COVERAGE": "Hubungan wali aktif untuk siswa",
    "pilotReadiness.check.ADMISSIONS_ACCESS": "Akses penerimaan siswa",
    "pilotReadiness.check.OPEN_ADMISSION_CYCLE": "Gelombang penerimaan terbuka",
    "pilotReadiness.check.OPEN_FOLLOWUPS": "Tindak lanjut terbuka",
    "pilotReadiness.check.FINANCE_ACCESS": "Akses keuangan",
    "pilotReadiness.check.FEE_CONFIGURATION": "Konfigurasi biaya aktif",
    "pilotReadiness.check.BILLING_CONFIGURATION": "Konfigurasi tagihan aktif",
    "pilotReadiness.check.ONLINE_PAYMENT_PROVIDER": "Penyedia pembayaran online",
    "pilotReadiness.check.IN_APP_COMMUNICATION": "Komunikasi di dalam aplikasi",
    "pilotReadiness.check.EXTERNAL_COMMUNICATION_PROVIDER": "Penyedia komunikasi eksternal",
    "pilotReadiness.action.REVIEW_SCHOOL_SETUP": "Periksa status dan pengaturan sekolah.",
    "pilotReadiness.action.REVIEW_ACADEMIC_ACCESS":
      "Pastikan operator memiliki akses akademik yang diperlukan.",
    "pilotReadiness.action.CONFIGURE_ACADEMIC_PERIOD": "Siapkan tahun ajaran untuk alur pilot.",
    "pilotReadiness.action.REVIEW_ACADEMIC_PERIOD": "Periksa periode aktif sesuai jadwal sekolah.",
    "pilotReadiness.action.ASSIGN_CLASSROOMS":
      "Siapkan setidaknya satu rombel yang akan digunakan.",
    "pilotReadiness.action.REVIEW_ENROLLMENTS": "Periksa data pendaftaran siswa untuk sekolah ini.",
    "pilotReadiness.action.REVIEW_CLASSROOM_ASSIGNMENTS":
      "Pastikan siswa pilot berada di rombel yang sesuai.",
    "pilotReadiness.action.ASSIGN_STUDENTS_TO_CLASSROOMS":
      "Tempatkan siswa pilot ke rombel melalui alur SIS yang ada.",
    "pilotReadiness.action.REVIEW_TEACHER_ASSIGNMENTS":
      "Periksa penugasan guru untuk kegiatan yang disepakati.",
    "pilotReadiness.action.REVIEW_STUDENT_PORTAL_ACCESS":
      "Periksa akun siswa melalui alur pengelolaan siswa.",
    "pilotReadiness.action.REVIEW_GUARDIAN_LINKS":
      "Periksa hubungan siswa dan wali melalui data wali.",
    "pilotReadiness.action.REVIEW_ADMISSIONS_ACCESS":
      "Pastikan operator penerimaan memiliki akses yang diperlukan.",
    "pilotReadiness.action.REVIEW_ADMISSION_CYCLE":
      "Periksa siklus penerimaan bila PPDB termasuk lingkup pilot.",
    "pilotReadiness.action.REVIEW_ADMISSIONS_FOLLOWUP": "Tinjau tindak lanjut yang belum selesai.",
    "pilotReadiness.action.REVIEW_FINANCE_ACCESS":
      "Pastikan operator keuangan memiliki akses yang diperlukan.",
    "pilotReadiness.action.CONFIGURE_FINANCE":
      "Tinjau konfigurasi biaya bila penagihan termasuk lingkup pilot.",
    "pilotReadiness.action.REVIEW_BILLING_SETUP":
      "Periksa konfigurasi tagihan yang akan digunakan.",
    "pilotReadiness.action.USE_MANUAL_PAYMENT_FALLBACK":
      "Penyedia online belum tersedia. Gunakan proses pembayaran manual yang didukung.",
    "pilotReadiness.action.USE_IN_APP_COMMUNICATION":
      "Gunakan pengumuman dan notifikasi di dalam aplikasi; penyedia eksternal belum tersedia.",
    "navigation.parentPortal": "Portal orang tua",
    "navigation.studentPortal": "Portal siswa",
    "navigation.academicYears": "Tahun ajaran",
    "navigation.terms": "Semester",
    "navigation.gradeLevels": "Tingkat kelas",
    "navigation.classrooms": "Rombel",
    "navigation.subjects": "Mata pelajaran",
    "navigation.curricula": "Kurikulum",
    "navigation.calendar": "Kalender akademik",
    "navigation.studentProgression": "Kenaikan siswa",
    "navigation.guardians": "Orang tua/wali",
    "navigation.staff": "Staf",
    "navigation.sisImports": "Impor data siswa",
    "navigation.sisExport": "Ekspor data siswa",
    "navigation.teacherAssignments": "Penugasan guru",
    "navigation.schedule": "Jadwal",
    "navigation.mySchedule": "Jadwal saya",
    "navigation.attendance": "Presensi",
    "navigation.assessments": "Penilaian",
    "navigation.reportCards": "Rapor",
    "navigation.teachingJournal": "Jurnal mengajar",
    "navigation.journalMonitor": "Monitor jurnal",
    "navigation.staffAttendance": "Presensi staf",
    "navigation.overview": "Ringkasan",
    "navigation.scores": "Nilai",
    "navigation.billing": "Tagihan",
    "settings.title": "Pengaturan",
    "settings.description": "Atur bahasa dan tampilan yang nyaman untuk Anda.",
    "settings.preferences": "Preferensi",
    "settings.savedLocally": "Preferensi tersimpan di browser ini.",
    "dashboard.title": "Dasbor",
    "dashboard.description": "Ringkasan ruang kerja sekolah Anda.",
    "dashboard.organization": "Organisasi",
    "dashboard.school": "Sekolah",
    "dashboard.academicContext": "Konteks akademik",
    "dashboard.noSchool": "Belum ada sekolah yang dipilih",
    "dashboard.noYear": "Belum ada tahun ajaran yang terlihat untuk sekolah ini.",
    "dashboard.welcome": "Selamat datang kembali",
    "dashboard.workspaceReady": "Ruang kerja Anda siap digunakan.",
    "auth.signIn": "Masuk",
    "auth.signInDescription": "Masuk ke ruang kerja EduSmart SchoolOS",
    "auth.email": "Email",
    "auth.password": "Kata sandi",
    "auth.forgotPassword": "Lupa kata sandi?",
    "auth.backHome": "Kembali ke beranda",
    "auth.signingIn": "Sedang masuk…",
    "auth.forgotTitle": "Lupa kata sandi",
    "auth.forgotDescription": "Kami akan mengirimkan tautan pemulihan ke email Anda.",
    "auth.sendResetLink": "Kirim tautan pemulihan",
    "auth.sending": "Mengirim…",
    "auth.resetSent":
      "Jika akun dengan email {email} ada, tautan pemulihan sedang dikirim. Periksa kotak masuk dan spam Anda.",
    "auth.backToSignIn": "Kembali ke halaman masuk",
    "auth.newPasswordTitle": "Atur kata sandi baru",
    "auth.newPasswordDescription": "Pilih kata sandi yang belum pernah Anda gunakan.",
    "auth.passwordUpdated": "Kata sandi diperbarui. Anda akan diarahkan ke dasbor…",
    "auth.resetLinkInvalid":
      "Tautan pemulihan tidak ada atau sudah kedaluwarsa. Minta tautan baru dari halaman lupa kata sandi.",
    "auth.newPassword": "Kata sandi baru",
    "auth.confirmPassword": "Konfirmasi kata sandi",
    "auth.updatePassword": "Perbarui kata sandi",
    "auth.updating": "Menyimpan…",
    "auth.requestNewLink": "Minta tautan baru",
    "auth.useAtLeastEight": "Gunakan setidaknya 8 karakter.",
    "auth.passwordMismatch": "Kata sandi tidak cocok.",
    "public.signIn": "Masuk",
    "public.badge": "Ruang kerja sekolah",
    "public.title": "Satu ruang kerja untuk operasional sekolah",
    "public.description":
      "EduSmart membantu sekolah mengelola kegiatan akademik, siswa, komunikasi, dan layanan keluarga dalam satu tempat.",
    "public.configured": "Terintegrasi",
    "public.configuredDescription": "Modul sekolah dalam satu pengalaman yang konsisten.",
    "public.connected": "Aman",
    "public.connectedDescription": "Akses berbasis akun dan ruang kerja sekolah.",
    "public.ready": "Siap digunakan",
    "public.readyDescription": "Masuk untuk melanjutkan ke ruang kerja Anda.",
    "notifications.title": "Notifikasi",
    "notifications.aria": "Notifikasi",
    "notifications.unreadAria": "{count} notifikasi belum dibaca",
    "notifications.description": "Kotak masuk notifikasi dalam aplikasi Anda.",
    "notifications.unread": "belum dibaca",
    "notifications.caughtUp": "Semua sudah diperiksa",
    "notifications.empty": "Notifikasi dalam aplikasi baru akan muncul di sini.",
    "notifications.loadError": "Notifikasi tidak dapat dimuat",
    "notifications.tryAgain": "Coba lagi",
    "notifications.read": "Dibaca",
    "notifications.unreadLabel": "Belum dibaca",
    "notifications.open": "Buka",
    "notifications.openRequest": "Buka permintaan",
    "notifications.markRead": "Tandai sudah dibaca",
    "communication.title": "Pusat komunikasi",
    "communication.description": "Buat dan terbitkan pengumuman sekolah dengan aman.",
    "communication.new": "Pengumuman baru",
    "communication.empty": "Belum ada pengumuman",
    "communication.emptyDescription": "Simpan draf untuk memulai komunikasi sekolah.",
    "communication.open": "Buka",
    "communication.back": "Kembali ke Pusat komunikasi",
    "communication.meta": "{targets} target · {recipients} penerima · Dibuat {date}",
    "communication.publishedOn": "Diterbitkan {date}",
    "communication.draftVersion": "Draf · Versi terbaru {version}",
    "communication.audience": "Penerima:",
    "communication.targetEntries": "target",
    "communication.resolvedRecipients": "Penerima terpilih:",
    "communication.delivered": "Pengumuman ini dikirim ke kotak masuk Anda.",
    "communication.cancelEditing": "Batalkan perubahan",
    "communication.editDraft": "Ubah draf",
    "communication.saveDraft": "Simpan draf",
    "communication.publishing": "Menerbitkan…",
    "communication.publish": "Terbitkan",
    "communication.deliveryTitle": "Pengiriman eksternal",
    "communication.deliveryDescription":
      "Buat antrean untuk penyedia eksternal. Pesan tidak akan dikirim sampai penyedia dan pengiriman diaktifkan.",
    "communication.deliveryWhatsapp": "Antrekan WhatsApp",
    "communication.deliveryEmail": "Antrekan email",
    "communication.deliveryQueued": "Antrean dibuat",
    "communication.deliveryAlreadyQueued": "Sudah ada di antrean",
    "communication.deliveryQueueing": "Membuat antrean…",
    "communication.deliveryUnavailable": "Status pengiriman tidak dapat dimuat.",
    "communication.deliveryQueueFailed": "Permintaan pengiriman tidak dapat dibuat. Coba lagi.",
    "communication.deliveryStatus.queued": "Dalam antrean",
    "communication.deliveryStatus.processing": "Diproses",
    "communication.deliveryStatus.paused": "Dijeda",
    "communication.deliveryStatus.completed": "Selesai",
    "communication.deliveryStatus.completed_with_errors": "Selesai dengan kendala",
    "communication.deliveryStatus.failed": "Gagal",
    "communication.deliveryStatus.cancelled": "Dibatalkan",
    "communication.deliveryRecipients": "Penerima",
    "communication.deliveryPending": "Menunggu",
    "communication.deliverySent": "Diterima penyedia",
    "communication.deliveryFailed": "Gagal",
    "communication.deliverySkipped": "Dilewati",
    "communication.runWorker": "Jalankan pemroses pengembangan",
    "communication.workerRunning": "Memproses antrean…",
    "communication.processing": "Sedang diproses",
    "communication.retryable": "Dapat dicoba lagi",
    "communication.pause": "Jeda",
    "communication.resume": "Lanjutkan",
    "communication.retry": "Coba lagi",
    "communication.operationFailed": "Operasi pengiriman gagal. Periksa status lalu coba lagi.",
    "communication.recipientStatus": "Status penerima pengiriman",
    "communication.destinationUnavailable": "Kontak tidak tersedia",
    "communication.eligibility.eligible": "Kontak siap; persetujuan operasional aktif",
    "communication.eligibility.opted_out": "Tidak dapat dikirim; persetujuan dicabut",
    "communication.eligibility.consent_required": "Persetujuan operasional diperlukan",
    "communication.eligibility.contact_unverified": "Kontak belum diverifikasi sekolah",
    "communication.eligibility.not_supported": "Jenis penerima ini belum didukung",
    "communication.recipientStatus.pending": "Menunggu",
    "communication.recipientStatus.processing": "Sedang diproses",
    "communication.recipientStatus.sent": "Diterima oleh adapter simulasi",
    "communication.recipientStatus.delivered": "Status terkirim belum dibuktikan",
    "communication.recipientStatus.failed": "Gagal",
    "communication.recipientStatus.skipped": "Dilewati",
    "communication.recipientStatus.cancelled": "Dibatalkan",
    "communication.failure.WORKER_LEASE_EXPIRED": "Pemroses berhenti; lease kedaluwarsa",
    "communication.failure.TEST_TEMPORARY_FAILURE": "Gangguan sementara simulasi",
    "communication.failure.TEST_INVALID_DESTINATION": "Tujuan simulasi tidak valid",
    "communication.failure.TEST_MISSING_DESTINATION": "Kontak tidak tersedia",
    "communication.failure.TEST_UNSUPPORTED_DESTINATION":
      "Tujuan tidak termasuk data simulasi yang diizinkan",
    "communication.failure.CONSENT_OR_CONTACT_INELIGIBLE":
      "Persetujuan atau kontak tidak memenuhi syarat",
    "communication.failure.RECIPIENT_NOT_SUPPORTED": "Jenis penerima tidak didukung",
    "communication.failure.CONTACT_NOT_IN_SCHOOL": "Kontak tidak aktif di sekolah ini",
    "communication.failure.DESTINATION_MISSING": "Kontak tidak tersedia",
    "communication.failure.CLAIM_EXPIRED": "Lease pemrosesan kedaluwarsa",
    "communication.failure.JOB_PAUSED": "Antrean dijeda",
    "communication.failure.INELIGIBLE": "Kontak tidak memenuhi syarat",
    "communication.consentEvidence": "Referensi bukti persetujuan dan verifikasi sekolah",
    "communication.recordConsent": "Catat persetujuan operasional",
    "communication.recordOptOut": "Catat penolakan/penarikan",
    "communication.deliveryNotSent":
      "Belum ada penyedia yang terhubung. Status antrean bukan bukti pesan telah dikirim.",
    "finance.title": "Keuangan",
    "finance.description": "Piutang operasional untuk sekolah aktif.",
    "finance.issued": "Diterbitkan",
    "finance.collected": "Terkumpul",
    "finance.outstanding": "Belum dibayar",
    "finance.overdue": "Jatuh tempo",
    "finance.receivables": "Piutang",
    "finance.idr": "Rupiah Indonesia",
    "payment.online.title": "Pembayaran online",
    "payment.online.pending": "Menunggu pembayaran",
    "payment.online.settled": "Lunas",
    "payment.online.expired": "Kedaluwarsa",
    "payment.online.unavailable": "Pembayaran online tidak tersedia",
    "payment.online.developmentOnly": "Simulasi pengembangan; tidak ada pembayaran nyata",
    "payment.online.reviewRequired": "Perlu ditinjau oleh bagian keuangan",
    "payment.online.create": "Buat pembayaran online",
    "payment.online.amount": "Jumlah pembayaran",
    "payment.online.expires": "Berlaku sampai",
    "payment.online.createError": "Pembayaran online tidak dapat dibuat. Silakan coba lagi.",
    "payment.online.event.pending": "Catat simulasi menunggu",
    "payment.online.event.settled": "Catat simulasi lunas",
    "payment.online.event.expired": "Catat simulasi kedaluwarsa",
    "payment.online.event.failed": "Catat simulasi gagal",
    "payment.online.noIntent": "Belum ada pembayaran online",
    "payment.online.failedStatus": "Gagal",
    "payment.online.cancelled": "Dibatalkan",
    "payment.online.operationError": "Tindakan pembayaran online tidak dapat dilakukan.",
    "payment.qris.title": "Bayar dengan QRIS",
    "payment.qris.sandbox": "SANDBOX / UJI COBA",
    "payment.qris.noRealMoney": "Pembayaran ini tidak menggunakan uang nyata.",
    "payment.qris.pay": "Bayar dengan QRIS (Sandbox)",
    "payment.qris.refresh": "Periksa status pembayaran",
    "payment.qris.qrAccessibleName": "Kode QRIS sandbox untuk pembayaran tagihan ini",
    "payment.qris.scanSandbox":
      "Hanya untuk simulator sandbox Midtrans. Jangan pindai dengan aplikasi pembayaran nyata.",
    "payment.qris.manualFallback":
      "Jika QRIS tidak tersedia, gunakan metode pembayaran manual yang disepakati dengan sekolah.",
    "payment.qris.disabledOutsideDevelopment": "Dinonaktifkan di luar Development",
    "payment.qris.notConfigured": "QRIS Sandbox belum dikonfigurasi.",
    "payment.qris.configured": "QRIS Sandbox tersedia untuk pembayaran uji coba.",
    "portal.parentEyebrow": "Portal Orang Tua",
    "portal.parentTitle": "Ruang keluarga",
    "portal.parentDescription":
      "Lihat informasi akademik anak yang telah diterbitkan oleh sekolah.",
    "portal.parentLoadError": "Data anak tidak dapat dimuat",
    "portal.parentEmptyTitle": "Belum ada anak yang tertaut ke akun ini",
    "portal.parentEmptyDescription":
      "Hubungi kantor sekolah untuk menyelesaikan penautan akun orang tua/wali.",
    "portal.studentEyebrow": "Portal Siswa",
    "portal.studentTitle": "Ruang belajar saya",
    "portal.studentDescription":
      "Lihat informasi akademik Anda yang telah diterbitkan oleh sekolah.",
    "portal.studentLoadError": "Data portal siswa tidak dapat dimuat",
    "portal.studentEmptyTitle": "Akun Portal Siswa belum tertaut",
    "portal.studentEmptyDescription":
      "Hubungi kantor sekolah untuk menautkan akun Anda ke data siswa.",
  },
  en: {
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.retry": "Try again",
    "common.settings": "Settings",
    "common.signOut": "Sign out",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.language": "Language",
    "common.appearance": "Appearance",
    "common.loading": "Loading…",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.page": "Page",
    "common.records": "records",
    "admissions.applicationCount": "{count} bounded results in the selected cycle.",
    "common.loadError": "We couldn't load this data",
    "common.loadErrorDescription":
      "Try again. If the problem continues, contact your school administrator.",
    "common.saving": "Saving…",
    "common.accessDenied": "You don't have access to this area",
    "common.accessDeniedDescription":
      "Access is required in the active workspace to view this data.",
    "common.selectOrganization": "Select an organization first",
    "common.selectOrganizationDescription": "Choose an organization in the top bar to continue.",
    "common.selectSchoolFirst": "Select a school first",
    "academic.selectSchoolDescription":
      "Academic data is scoped to the selected school. Choose a school in the top bar to continue.",
    "common.status.active": "Active",
    "common.status.inactive": "Inactive",
    "common.status.draft": "Draft",
    "common.status.published": "Published",
    "common.status.submitted": "Submitted",
    "common.status.accepted": "Accepted",
    "common.status.rejected": "Rejected",
    "common.status.withdrawn": "Withdrawn",
    "common.status.open": "Open",
    "common.status.closed": "Closed",
    "common.status.archived": "Archived",
    "common.status.issued": "Issued",
    "common.status.paid": "Paid",
    "common.status.unpaid": "Unpaid",
    "common.status.overdue": "Overdue",
    "common.status.void": "Void",
    "common.status.cancelled": "Cancelled",
    "common.status.expired": "Expired",
    "common.status.missing": "Missing",
    "common.status.excused": "Excused",
    "common.status.final": "Final",
    "common.noOrganization": "No organization",
    "common.selectSchool": "Select school",
    "common.academicYear": "Academic year",
    "common.term": "Term",
    "common.noAcademicYear": "No academic year",
    "common.noTerm": "No term",
    "common.account": "Account",
    "common.version": "Version",
    "common.openNavigation": "Open navigation",
    "common.closeNavigation": "Close navigation",
    "common.dismissNavigationOverlay": "Close navigation menu",
    "common.navigationMenu": "Navigation menu",
    "common.workspace": "Workspace",
    "navigation.dashboard": "Dashboard",
    "navigation.notifications": "Notifications",
    "navigation.permissionRequests": "Permission Requests",
    "permissionRequests.activeSchool": "active school",
    "permissionRequests.staffDescription": "Staff workflow for {school}.",
    "permissionRequests.serverPage": "Server page {page}",
    "navigation.communication": "Communication Center",
    "navigation.academicSetup": "Academic Setup",
    "navigation.academicOperations": "Academic Operations",
    "navigation.students": "Students",
    "navigation.studentInformation": "Student Information",
    "navigation.admissions": "Admissions",
    "navigation.finance": "Finance",
    "navigation.schoolOperations": "School Operations",
    "navigation.pilotReadiness": "Pilot Readiness",
    "pilotReadiness.title": "School pilot readiness",
    "pilotReadiness.description":
      "A read-only summary of the agreed pilot workflows, computed from the school's current state.",
    "pilotReadiness.overall": "Readiness summary",
    "pilotReadiness.overallExplanation": "The highest risk check determines the overall status.",
    "pilotReadiness.domains": "Checks by domain",
    "pilotReadiness.refresh": "Refresh checks",
    "pilotReadiness.reviewLink": "Review setup",
    "pilotReadiness.count": "Count: {count}",
    "pilotReadiness.generatedAt": "Computed {date}",
    "pilotReadiness.error":
      "Readiness could not be loaded. Try again or contact the school administrator.",
    "pilotReadiness.denied": "You do not have access to this school's readiness summary.",
    "pilotReadiness.syntheticDisclaimer":
      "This technical result does not mean the school has accepted a pilot. Confirm workflows and owners with the school.",
    "pilotReadiness.status.READY": "Ready",
    "pilotReadiness.status.WARNING": "Review needed",
    "pilotReadiness.status.BLOCKER": "Blocker",
    "pilotReadiness.status.MANUAL_FALLBACK": "Manual fallback",
    "pilotReadiness.domain.school": "School",
    "pilotReadiness.domain.academic_sis": "Academics and student data",
    "pilotReadiness.domain.teaching": "Teacher operations",
    "pilotReadiness.domain.portals": "Student and parent portals",
    "pilotReadiness.domain.admissions": "Admissions",
    "pilotReadiness.domain.finance": "Finance",
    "pilotReadiness.domain.communication": "Communication",
    "pilotReadiness.check.SCHOOL_ACTIVE": "School status",
    "pilotReadiness.check.ACADEMIC_ACCESS": "Academic setup access",
    "pilotReadiness.check.ACTIVE_ACADEMIC_YEAR": "Active academic year",
    "pilotReadiness.check.ACTIVE_TERM": "Active academic period",
    "pilotReadiness.check.ACTIVE_CLASSROOMS": "Active classrooms",
    "pilotReadiness.check.ACTIVE_ENROLLMENTS": "Active student enrollments",
    "pilotReadiness.check.CLASSROOM_ASSIGNMENT_COVERAGE": "Student classroom placement",
    "pilotReadiness.check.TEACHING_ACCESS": "Teacher assignment access",
    "pilotReadiness.check.ACTIVE_TEACHER_ASSIGNMENTS": "Active teacher assignments",
    "pilotReadiness.check.STUDENT_PORTAL_ACCESS": "Student portal data access",
    "pilotReadiness.check.STUDENT_ACCOUNT_LINKS": "Student accounts linked to active enrollments",
    "pilotReadiness.check.GUARDIAN_LINK_COVERAGE": "Active guardian links for enrolled students",
    "pilotReadiness.check.ADMISSIONS_ACCESS": "Admissions access",
    "pilotReadiness.check.OPEN_ADMISSION_CYCLE": "Open admission cycle",
    "pilotReadiness.check.OPEN_FOLLOWUPS": "Open follow-ups",
    "pilotReadiness.check.FINANCE_ACCESS": "Finance access",
    "pilotReadiness.check.FEE_CONFIGURATION": "Active fee configuration",
    "pilotReadiness.check.BILLING_CONFIGURATION": "Active billing configuration",
    "pilotReadiness.check.ONLINE_PAYMENT_PROVIDER": "Online payment provider",
    "pilotReadiness.check.IN_APP_COMMUNICATION": "In-app communication",
    "pilotReadiness.check.EXTERNAL_COMMUNICATION_PROVIDER": "External communication provider",
    "pilotReadiness.action.REVIEW_SCHOOL_SETUP": "Review the school's status and settings.",
    "pilotReadiness.action.REVIEW_ACADEMIC_ACCESS":
      "Ensure the operator has the required academic access.",
    "pilotReadiness.action.CONFIGURE_ACADEMIC_PERIOD":
      "Set up an academic year for the pilot workflow.",
    "pilotReadiness.action.REVIEW_ACADEMIC_PERIOD":
      "Check that the active period matches the school calendar.",
    "pilotReadiness.action.ASSIGN_CLASSROOMS": "Set up at least one classroom for the pilot.",
    "pilotReadiness.action.REVIEW_ENROLLMENTS": "Review student enrollment data for this school.",
    "pilotReadiness.action.REVIEW_CLASSROOM_ASSIGNMENTS":
      "Ensure pilot students are placed in the right classrooms.",
    "pilotReadiness.action.ASSIGN_STUDENTS_TO_CLASSROOMS":
      "Place pilot students through the existing SIS workflow.",
    "pilotReadiness.action.REVIEW_TEACHER_ASSIGNMENTS":
      "Review teacher assignments for the agreed activities.",
    "pilotReadiness.action.REVIEW_STUDENT_PORTAL_ACCESS":
      "Review student accounts through the existing student workflow.",
    "pilotReadiness.action.REVIEW_GUARDIAN_LINKS":
      "Review student-guardian links in guardian records.",
    "pilotReadiness.action.REVIEW_ADMISSIONS_ACCESS":
      "Ensure the admissions operator has the required access.",
    "pilotReadiness.action.REVIEW_ADMISSION_CYCLE":
      "Review the admission cycle if PPDB is in pilot scope.",
    "pilotReadiness.action.REVIEW_ADMISSIONS_FOLLOWUP": "Review follow-ups that are still open.",
    "pilotReadiness.action.REVIEW_FINANCE_ACCESS":
      "Ensure the finance operator has the required access.",
    "pilotReadiness.action.CONFIGURE_FINANCE": "Review fee setup if billing is in pilot scope.",
    "pilotReadiness.action.REVIEW_BILLING_SETUP": "Review billing configuration for the pilot.",
    "pilotReadiness.action.USE_MANUAL_PAYMENT_FALLBACK":
      "Online provider is unavailable. Use the supported manual payment process.",
    "pilotReadiness.action.USE_IN_APP_COMMUNICATION":
      "Use in-app announcements and notifications; external providers are unavailable.",
    "navigation.parentPortal": "Parent Portal",
    "navigation.studentPortal": "Student Portal",
    "navigation.academicYears": "Academic Years",
    "navigation.terms": "Terms",
    "navigation.gradeLevels": "Grade Levels",
    "navigation.classrooms": "Classrooms",
    "navigation.subjects": "Subjects",
    "navigation.curricula": "Curricula",
    "navigation.calendar": "Academic Calendar",
    "navigation.studentProgression": "Student Progression",
    "navigation.guardians": "Guardians",
    "navigation.staff": "Staff",
    "navigation.sisImports": "SIS Imports",
    "navigation.sisExport": "SIS Export",
    "navigation.teacherAssignments": "Teacher Assignments",
    "navigation.schedule": "Schedule",
    "navigation.mySchedule": "My Schedule",
    "navigation.attendance": "Attendance",
    "navigation.assessments": "Assessments",
    "navigation.reportCards": "Report Cards",
    "navigation.teachingJournal": "Teaching Journal",
    "navigation.journalMonitor": "Journal Monitor",
    "navigation.staffAttendance": "Staff Attendance",
    "navigation.overview": "Overview",
    "navigation.scores": "Scores",
    "navigation.billing": "Billing",
    "settings.title": "Settings",
    "settings.description": "Choose the language and appearance that work best for you.",
    "settings.preferences": "Preferences",
    "settings.savedLocally": "Preferences are saved in this browser.",
    "dashboard.title": "Dashboard",
    "dashboard.description": "An overview of your school workspace.",
    "dashboard.organization": "Organization",
    "dashboard.school": "School",
    "dashboard.academicContext": "Academic context",
    "dashboard.noSchool": "No school selected",
    "dashboard.noYear": "No academic year is visible for this school.",
    "dashboard.welcome": "Welcome back",
    "dashboard.workspaceReady": "Your workspace is ready.",
    "auth.signIn": "Sign in",
    "auth.signInDescription": "Sign in to your EduSmart SchoolOS workspace",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.backHome": "Back home",
    "auth.signingIn": "Signing in…",
    "auth.forgotTitle": "Forgot password",
    "auth.forgotDescription": "We'll email you a reset link.",
    "auth.sendResetLink": "Send reset link",
    "auth.sending": "Sending…",
    "auth.resetSent":
      "If an account exists for {email}, a reset link is on its way. Check your inbox and spam folder.",
    "auth.backToSignIn": "Back to sign in",
    "auth.newPasswordTitle": "Set a new password",
    "auth.newPasswordDescription": "Choose a password you haven't used before.",
    "auth.passwordUpdated": "Password updated. Taking you to your dashboard…",
    "auth.resetLinkInvalid":
      "This reset link is missing or expired. Request a new one from the forgot password page.",
    "auth.newPassword": "New password",
    "auth.confirmPassword": "Confirm password",
    "auth.updatePassword": "Update password",
    "auth.updating": "Saving…",
    "auth.requestNewLink": "Request new link",
    "auth.useAtLeastEight": "Use at least 8 characters.",
    "auth.passwordMismatch": "Passwords do not match.",
    "public.signIn": "Sign in",
    "public.badge": "School workspace",
    "public.title": "One workspace for school operations",
    "public.description":
      "EduSmart helps schools manage academics, students, communication, and family services in one place.",
    "public.configured": "Connected",
    "public.configuredDescription": "School modules in one consistent experience.",
    "public.connected": "Secure",
    "public.connectedDescription": "Account-based access scoped to your school workspace.",
    "public.ready": "Ready to use",
    "public.readyDescription": "Sign in to continue to your workspace.",
    "notifications.title": "Notifications",
    "notifications.aria": "Notifications",
    "notifications.unreadAria": "{count} unread notifications",
    "notifications.description": "Your authenticated in-app notification inbox.",
    "notifications.unread": "unread",
    "notifications.caughtUp": "You're all caught up",
    "notifications.empty": "New in-app notifications will appear here.",
    "notifications.loadError": "We couldn't load notifications",
    "notifications.tryAgain": "Try again",
    "notifications.read": "Read",
    "notifications.unreadLabel": "Unread",
    "notifications.open": "Open",
    "notifications.openRequest": "Open request",
    "notifications.markRead": "Mark read",
    "communication.title": "Communication Center",
    "communication.description": "Create and publish secure school announcements.",
    "communication.new": "New announcement",
    "communication.empty": "No announcements yet",
    "communication.emptyDescription": "Save a draft to start a school communication.",
    "communication.open": "Open",
    "communication.back": "Back to Communication Center",
    "communication.meta": "{targets} targets · {recipients} recipients · Created {date}",
    "communication.publishedOn": "Published {date}",
    "communication.draftVersion": "Draft · Updated version {version}",
    "communication.audience": "Audience:",
    "communication.targetEntries": "target entries",
    "communication.resolvedRecipients": "Resolved recipients:",
    "communication.delivered": "This announcement was delivered to your authenticated inbox.",
    "communication.cancelEditing": "Cancel editing",
    "communication.editDraft": "Edit draft",
    "communication.saveDraft": "Save draft",
    "communication.publishing": "Publishing…",
    "communication.publish": "Publish",
    "communication.deliveryTitle": "External delivery",
    "communication.deliveryDescription":
      "Create a request for an external provider. No message is sent until a provider and dispatch worker are enabled.",
    "communication.deliveryWhatsapp": "Queue WhatsApp",
    "communication.deliveryEmail": "Queue email",
    "communication.deliveryQueued": "Request queued",
    "communication.deliveryAlreadyQueued": "Already queued",
    "communication.deliveryQueueing": "Queuing…",
    "communication.deliveryUnavailable": "Delivery status could not be loaded.",
    "communication.deliveryQueueFailed": "The delivery request could not be queued. Try again.",
    "communication.deliveryStatus.queued": "Queued",
    "communication.deliveryStatus.processing": "Processing",
    "communication.deliveryStatus.paused": "Paused",
    "communication.deliveryStatus.completed": "Completed",
    "communication.deliveryStatus.completed_with_errors": "Completed with issues",
    "communication.deliveryStatus.failed": "Failed",
    "communication.deliveryStatus.cancelled": "Cancelled",
    "communication.deliveryRecipients": "Recipients",
    "communication.deliveryPending": "Pending",
    "communication.deliverySent": "Provider accepted",
    "communication.deliveryFailed": "Failed",
    "communication.deliverySkipped": "Skipped",
    "communication.runWorker": "Run Development executor",
    "communication.workerRunning": "Processing queue…",
    "communication.processing": "Processing",
    "communication.retryable": "Retry eligible",
    "communication.pause": "Pause",
    "communication.resume": "Resume",
    "communication.retry": "Retry",
    "communication.operationFailed": "Delivery operation failed. Review the status and try again.",
    "communication.recipientStatus": "Delivery recipient status",
    "communication.destinationUnavailable": "Contact unavailable",
    "communication.eligibility.eligible": "Contact ready; operational consent is active",
    "communication.eligibility.opted_out": "Ineligible; consent was withdrawn",
    "communication.eligibility.consent_required": "Operational consent required",
    "communication.eligibility.contact_unverified": "Contact is not school-verified",
    "communication.eligibility.not_supported": "This recipient type is not supported yet",
    "communication.recipientStatus.pending": "Pending",
    "communication.recipientStatus.processing": "Processing",
    "communication.recipientStatus.sent": "Accepted by the test adapter",
    "communication.recipientStatus.delivered": "Delivery is not confirmed",
    "communication.recipientStatus.failed": "Failed",
    "communication.recipientStatus.skipped": "Skipped",
    "communication.recipientStatus.cancelled": "Cancelled",
    "communication.failure.WORKER_LEASE_EXPIRED": "Executor stopped; lease expired",
    "communication.failure.TEST_TEMPORARY_FAILURE": "Simulated temporary failure",
    "communication.failure.TEST_INVALID_DESTINATION": "Simulated invalid destination",
    "communication.failure.TEST_MISSING_DESTINATION": "Contact unavailable",
    "communication.failure.TEST_UNSUPPORTED_DESTINATION":
      "Destination is outside the allowed synthetic test set",
    "communication.failure.CONSENT_OR_CONTACT_INELIGIBLE": "Consent or contact is ineligible",
    "communication.failure.RECIPIENT_NOT_SUPPORTED": "Recipient type is unsupported",
    "communication.failure.CONTACT_NOT_IN_SCHOOL": "Contact is not active at this school",
    "communication.failure.DESTINATION_MISSING": "Contact unavailable",
    "communication.failure.CLAIM_EXPIRED": "Execution lease expired",
    "communication.failure.JOB_PAUSED": "Job is paused",
    "communication.failure.INELIGIBLE": "Contact is ineligible",
    "communication.consentEvidence": "Consent and school verification evidence reference",
    "communication.recordConsent": "Record operational consent",
    "communication.recordOptOut": "Record opt-out/revocation",
    "communication.deliveryNotSent":
      "No provider is connected. A queued status does not mean a message was sent.",
    "finance.title": "Finance",
    "finance.description": "Operational receivables for the active school.",
    "finance.issued": "Issued",
    "finance.collected": "Collected",
    "finance.outstanding": "Outstanding",
    "finance.overdue": "Overdue",
    "finance.receivables": "Receivables",
    "finance.idr": "Indonesian rupiah",
    "payment.online.title": "Online payment",
    "payment.online.pending": "Awaiting payment",
    "payment.online.settled": "Settled",
    "payment.online.expired": "Expired",
    "payment.online.unavailable": "Online payment is unavailable",
    "payment.online.developmentOnly": "Development simulation; no real payment",
    "payment.online.reviewRequired": "Finance review required",
    "payment.online.create": "Create online payment",
    "payment.online.amount": "Payment amount",
    "payment.online.expires": "Expires at",
    "payment.online.createError": "Online payment could not be created. Please try again.",
    "payment.online.event.pending": "Record pending simulation",
    "payment.online.event.settled": "Record settled simulation",
    "payment.online.event.expired": "Record expired simulation",
    "payment.online.event.failed": "Record failed simulation",
    "payment.online.noIntent": "No online payment yet",
    "payment.online.failedStatus": "Failed",
    "payment.online.cancelled": "Cancelled",
    "payment.online.operationError": "The online payment action could not be completed.",
    "payment.qris.title": "Pay with QRIS",
    "payment.qris.sandbox": "SANDBOX / TEST PAYMENT",
    "payment.qris.noRealMoney": "This payment does not use real money.",
    "payment.qris.pay": "Pay with QRIS (Sandbox)",
    "payment.qris.refresh": "Refresh payment status",
    "payment.qris.qrAccessibleName": "Sandbox QRIS code for this invoice payment",
    "payment.qris.scanSandbox":
      "For the Midtrans sandbox simulator only. Do not scan with a real payment app.",
    "payment.qris.manualFallback":
      "If QRIS is unavailable, use the manual payment method agreed with the school.",
    "payment.qris.disabledOutsideDevelopment": "Disabled outside Development",
    "payment.qris.notConfigured": "QRIS Sandbox is not configured.",
    "payment.qris.configured": "QRIS Sandbox is available for test payments.",
    "portal.parentEyebrow": "Parent Portal",
    "portal.parentTitle": "Family workspace",
    "portal.parentDescription": "View your child's academic information published by the school.",
    "portal.parentLoadError": "We couldn't load your children's information",
    "portal.parentEmptyTitle": "No children linked to this account",
    "portal.parentEmptyDescription":
      "Contact the school office to complete the guardian account link.",
    "portal.studentEyebrow": "Student Portal",
    "portal.studentTitle": "My learning space",
    "portal.studentDescription": "View your academic information published by the school.",
    "portal.studentLoadError": "We couldn't load Student Portal information",
    "portal.studentEmptyTitle": "No Student Portal account linked",
    "portal.studentEmptyDescription":
      "Contact the school office to link your login to a student record.",
  },
} as const;

type MessageKey = keyof typeof messages.en;

type PreferencesContextValue = {
  locale: Locale;
  theme: Theme;
  setLocale: (locale: Locale) => void;
  setTheme: (theme: Theme) => void;
  t: (key: MessageKey, values?: Record<string, string>) => string;
  formatDate: (value: string | number | Date, options?: Intl.DateTimeFormatOptions) => string;
  formatNumber: (value: number, options?: Intl.NumberFormatOptions) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

const sharedCopy: Record<string, string> = {
  "Schedule change rejected": "Perubahan jadwal ditolak",
  Publish: "Terbitkan",
  Archive: "Arsipkan",
  Edit: "Ubah",
  "Classroom schedule": "Jadwal kelas",
  "My schedule": "Jadwal saya",
  "New draft": "Draf baru",
  "Select an academic year and term": "Pilih tahun ajaran dan semester",
  "We couldn't load the schedule": "Jadwal tidak dapat dimuat",
  Retry: "Coba lagi",
  "Schedule entry published.": "Jadwal berhasil diterbitkan.",
  "Schedule entry archived.": "Jadwal berhasil diarsipkan.",
  "The schedule change could not be completed. Refresh and try again.":
    "Perubahan jadwal tidak dapat diselesaikan. Muat ulang dan coba lagi.",
  "Schedule data is temporarily unavailable. Please retry.":
    "Data jadwal sementara tidak tersedia. Silakan coba lagi.",
  "Your teaching timetable in the active academic context.":
    "Jadwal mengajar Anda pada konteks akademik aktif.",
  "Plan, publish and preserve classroom and teacher timetables.":
    "Rencanakan, terbitkan, dan simpan jadwal kelas serta guru.",
  "All teachers": "Semua guru",
  "Classroom filter": "Filter kelas",
  "Teacher filter": "Filter guru",
  Period: "Periode",
  Room: "Ruang",
  "Effective from": "Berlaku mulai",
  "Effective to": "Berlaku hingga",
  "Successor cutover date": "Tanggal pergantian jadwal",
  "The predecessor ends on the day before this date.":
    "Jadwal sebelumnya berakhir sehari sebelum tanggal ini.",
  "Choose assignment": "Pilih penugasan",
  "Choose period": "Pilih periode",
  "Draft · staff only": "Draf · khusus staf",
  "Inactive history": "Riwayat nonaktif",
  Monday: "Senin",
  Tuesday: "Selasa",
  Wednesday: "Rabu",
  Thursday: "Kamis",
  Friday: "Jumat",
  Saturday: "Sabtu",
  Sunday: "Minggu",
  "Published successor created.": "Jadwal pengganti berhasil dibuat.",
  "Draft saved.": "Draf berhasil disimpan.",
  "We couldn't load your overview": "Ringkasan tidak dapat dimuat",
  "We couldn't load your schedule": "Jadwal tidak dapat dimuat",
  "We couldn't load attendance": "Presensi tidak dapat dimuat",
  "We couldn't load results": "Hasil penilaian tidak dapat dimuat",
  "We couldn't load report cards": "Rapor tidak dapat dimuat",
  "We couldn't load this child's overview": "Ringkasan anak tidak dapat dimuat",
  "We couldn't load Report Cards": "Rapor tidak dapat dimuat",
  "Set by the school on your guardian record.": "Diatur sekolah pada data orang tua/wali Anda.",
  "Attendance summary": "Ringkasan presensi",
  "Homeroom comment": "Catatan wali kelas",
  "Official PDF": "PDF resmi",
  "No permission requests": "Tidak ada permintaan izin",
  "Requests shared with your account will appear here.":
    "Permintaan yang dibagikan kepada akun Anda akan muncul di sini.",
  "We couldn't load permission requests": "Permintaan izin tidak dapat dimuat",
  "We couldn't load this permission request": "Permintaan izin ini tidak dapat dimuat",
  "Request details": "Rincian permintaan",
  "Refresh required": "Perlu dimuat ulang",
  "Decision not saved": "Keputusan belum tersimpan",
  "No student details available": "Rincian siswa tidak tersedia",
  "Decision history": "Riwayat keputusan",
  "Staff Attendance": "Presensi Staf",
  "School-scoped operational attendance and read-only personal history.":
    "Presensi operasional lingkup sekolah dan riwayat pribadi hanya-baca.",
  "Edit attendance record": "Ubah catatan presensi",
  "Create attendance record": "Buat catatan presensi",
  "Action not completed": "Tindakan belum selesai",
  "Attendance Date": "Tanggal presensi",
  "Check-in": "Waktu masuk",
  "Check-out": "Waktu pulang",
  Note: "Catatan",
  "School attendance": "Presensi sekolah",
  "Manager view is bounded and school-scoped.": "Tampilan pengelola dibatasi pada lingkup sekolah.",
  "Attendance unavailable": "Data presensi tidak tersedia",
  "My attendance history": "Riwayat presensi saya",
  "Read-only history for the authenticated staff identity.":
    "Riwayat baca-saja untuk identitas staf yang masuk.",
  "Attendance history unavailable": "Riwayat presensi tidak tersedia",
  "Access unavailable": "Akses tidak tersedia",
  "Page not found": "Halaman tidak ditemukan",
  "The page you're looking for doesn't exist or has been moved.":
    "Halaman yang Anda cari tidak tersedia atau telah dipindahkan.",
  "Go home": "Kembali ke beranda",
  "This page didn't load": "Halaman ini tidak dapat dimuat",
  "Something went wrong on our end. You can try refreshing or head back home.":
    "Terjadi kesalahan. Coba muat ulang halaman atau kembali ke beranda.",
  "Your active account does not have a Teaching Journal permission.":
    "Akun aktif Anda tidak memiliki izin untuk Jurnal Mengajar.",
  "Your active account does not have Staff Attendance permission.":
    "Akun aktif Anda tidak memiliki izin untuk Presensi Staf.",
  "Billing is available only to an authorized related parent.":
    "Tagihan hanya tersedia bagi orang tua/wali yang terhubung dan berwenang.",
  "Review and respond to permission requests for your children.":
    "Tinjau dan tanggapi permintaan izin untuk anak Anda.",
  "Teaching journals": "Jurnal mengajar",
  "Journal monitor unavailable": "Monitor jurnal tidak tersedia",
  "Report card draft created.": "Draf rapor berhasil dibuat.",
  "Selected term is not part of this enrollment's academic year.":
    "Semester yang dipilih bukan bagian dari tahun ajaran pendaftaran ini.",
  "Search student": "Cari siswa",
  "Student enrollment": "Pendaftaran siswa",
  "Candidates could not be loaded": "Kandidat tidak dapat dimuat",
  "No eligible student enrollments": "Tidak ada pendaftaran siswa yang memenuhi syarat",
  "Student candidates could not be loaded. Please retry.":
    "Kandidat siswa tidak dapat dimuat. Silakan coba lagi.",
  "Report card data could not be loaded.": "Data rapor tidak dapat dimuat.",
  "Report card data could not be loaded. Please retry.":
    "Data rapor tidak dapat dimuat. Silakan coba lagi.",
  "No active enrollments in your authorized scope match this search.":
    "Tidak ada pendaftaran aktif dalam lingkup akses Anda yang sesuai dengan pencarian ini.",
  "Generation result is uncertain": "Hasil pembuatan belum dapat dipastikan",
  "Report card access unavailable": "Akses rapor tidak tersedia",
  "Report cards could not be loaded": "Rapor tidak dapat dimuat",
  "No report cards found": "Rapor tidak ditemukan",
  "Attendance snapshot": "Ringkasan presensi",
  "finalized sessions": "sesi yang dikunci",
  "No subject snapshots": "Belum ada ringkasan mata pelajaran",
  "Narrative sections": "Bagian narasi",
  "Add narrative section": "Tambah bagian narasi",
  "Workflow result is uncertain": "Hasil alur kerja belum dapat dipastikan",
  "Report card workflow updated.": "Alur kerja rapor berhasil diperbarui.",
  "Official PDF is available.": "PDF resmi tersedia.",
  "PDF generation failed": "Pembuatan PDF gagal",
  "Official PDF regenerated.": "PDF resmi berhasil dibuat ulang.",
  "PDF regeneration failed": "Pembuatan ulang PDF gagal",
  "Secure download failed.": "Unduhan aman gagal.",
  "Document status unavailable": "Status dokumen tidak tersedia",
  "Report card saved.": "Rapor berhasil disimpan.",
  "Draft created.": "Draf berhasil dibuat.",
  "Announcement published.": "Pengumuman berhasil diterbitkan.",
  "The announcement could not be saved. Please try again.":
    "Pengumuman tidak dapat disimpan. Silakan coba lagi.",
  "The announcement could not be published. Please try again.":
    "Pengumuman tidak dapat diterbitkan. Silakan coba lagi.",
  "Academic Years": "Tahun Ajaran",
  "Closure recorded": "Penutupan dicatat",
  Window: "Periode",
  "Any time": "Kapan saja",
  "No closing date": "Tanpa tanggal penutupan",
  "No opening date": "Tanpa tanggal pembukaan",
  "Academic Year": "Tahun Ajaran",
  "Grade Levels": "Tingkat Kelas",
  "Grade level": "Tingkat kelas",
  Classrooms: "Rombongan Belajar",
  Classroom: "Rombongan Belajar",
  Subjects: "Mata Pelajaran",
  Subject: "Mata Pelajaran",
  Curricula: "Kurikulum",
  Curriculum: "Kurikulum",
  "Academic Calendar": "Kalender Akademik",
  Finance: "Keuangan",
  Fees: "Biaya",
  Billing: "Tagihan",
  Invoices: "Faktur",
  Invoice: "Faktur",
  Total: "Total",
  Outstanding: "Belum dibayar",
  Received: "Diterima",
  Reference: "Referensi",
  Amount: "Jumlah",
  Method: "Metode",
  Reversed: "Dibalik",
  Valid: "Valid",
  manual: "Manual",
  "Document:": "Dokumen:",
  Payments: "Pembayaran",
  "Finance overview": "Ringkasan keuangan",
  "Family workspace": "Ruang keluarga",
  Overview: "Ringkasan",
  Scores: "Nilai",
  "Student Portal": "Portal Siswa",
  "Parent Portal": "Portal Orang Tua/Wali",
  "Student progression": "Kenaikan siswa",
  "Student Progression": "Kenaikan siswa",
  Reporting: "Pelaporan",
  "Build and manage frozen academic snapshots through publication.":
    "Susun dan kelola rapor akademik yang dibekukan hingga diterbitkan.",
  "Reload latest data": "Muat ulang data terbaru",
  applied: "Diterapkan",
  promoted: "Naik kelas",
  retained: "Tinggal kelas",
  graduated: "Lulus",
  cancelled: "Dibatalkan",
  Students: "Siswa",
  Student: "Siswa",
  Guardians: "Orang Tua/Wali",
  Guardian: "Orang Tua/Wali",
  Staff: "Staf",
  Attendance: "Presensi",
  Assessment: "Penilaian",
  Assessments: "Penilaian",
  "New assessment": "Penilaian baru",
  "Create assessment": "Buat penilaian",
  "Teaching assignment": "Penugasan mengajar",
  "Choose class and subject": "Pilih kelas dan mata pelajaran",
  "Assessment draft created.": "Draf penilaian berhasil dibuat.",
  "Create assessments and manage scoring for the selected term.":
    "Buat penilaian dan kelola nilai untuk semester yang dipilih.",
  "No assessments in this term.": "Tidak ada penilaian pada semester ini.",
  "Select a school, academic year, and term to view assessments.":
    "Pilih sekolah, tahun ajaran, dan semester untuk melihat penilaian.",
  "Select a complete academic context.": "Pilih konteks akademik yang lengkap.",
  "Access unavailable.": "Akses tidak tersedia.",
  "Assigned class": "Kelas yang ditugaskan",
  "We couldn't load assessments. Please try again.":
    "Penilaian tidak dapat dimuat. Silakan coba lagi.",
  "The assessment action could not be completed. Please try again.":
    "Tindakan penilaian tidak dapat diselesaikan. Silakan coba lagi.",
  "Some scores could not be saved. Please review the roster and try again.":
    "Sebagian nilai tidak dapat disimpan. Periksa daftar siswa dan coba lagi.",
  "Assessment type": "Jenis penilaian",
  Date: "Tanggal",
  "Minimum score": "Nilai minimum",
  "Maximum score": "Nilai maksimum",
  "Weight (optional)": "Bobot (opsional)",
  "Description (optional)": "Deskripsi (opsional)",
  "Create a draft in the selected academic context.":
    "Buat draf dalam konteks akademik yang dipilih.",
  Score: "Nilai",
  Result: "Hasil",
  Feedback: "Umpan balik",
  "Corrected score": "Nilai yang dikoreksi",
  "Correction reason": "Alasan koreksi",
  "Scores saved.": "Nilai berhasil disimpan.",
  "Assessment status updated.": "Status penilaian berhasil diperbarui.",
  "Draft updated.": "Draf berhasil diperbarui.",
  "Final score corrected.": "Nilai akhir berhasil dikoreksi.",
  "Assessments are not available in this academic context.":
    "Penilaian tidak tersedia dalam konteks akademik ini.",
  "No assessments found.": "Penilaian tidak ditemukan.",
  "No students are available for this assessment.": "Tidak ada siswa untuk penilaian ini.",
  "Assessment unavailable.": "Penilaian tidak tersedia.",
  "Assessment details": "Detail penilaian",
  "Score entry": "Entri nilai",
  "students in the roster. Historical non-eligible scores remain visible and read-only.":
    "siswa dalam daftar. Nilai historis siswa yang tidak memenuhi syarat tetap ditampilkan dan hanya dapat dibaca.",
  "eligible students. Missing and excused results have no numeric score.":
    "siswa yang memenuhi syarat. Hasil belum diisi atau dikecualikan tidak memiliki nilai angka.",
  "Historical · read-only": "Historis · hanya dapat dibaca",
  Eligible: "Memenuhi syarat",
  "No students were enrolled in this class on the assessment date.":
    "Tidak ada siswa yang terdaftar di kelas ini pada tanggal penilaian.",
  "No student number": "Tidak ada nomor siswa",
  "Publish scores": "Terbitkan nilai",
  "Close scoring": "Tutup pengisian nilai",
  "Open scoring": "Buka pengisian nilai",
  "Save draft": "Simpan draf",
  "Save all scores": "Simpan semua nilai",
  "Saving…": "Menyimpan…",
  Correct: "Koreksi",
  "This assessment changed. Reload latest data before saving again.":
    "Penilaian ini berubah. Muat ulang data terbaru sebelum menyimpan kembali.",
  "Draft details": "Detail draf",
  "No scores have been entered.": "Belum ada nilai yang dimasukkan.",
  "No timetable periods": "Belum ada periode jadwal",
  "Create active timetable periods before adding schedule entries.":
    "Buat periode jadwal aktif sebelum menambahkan sesi jadwal.",
  "No schedule entries match this view": "Tidak ada jadwal yang sesuai dengan tampilan ini",
  "Create a draft or change the classroom and teacher filters.":
    "Buat draf atau ubah filter kelas dan guru.",
  "Frozen subject snapshot": "Snapshot mata pelajaran yang dibekukan",
  "Final score": "Nilai akhir",
  Predicate: "Predikat",
  "No content": "Tidak ada konten",
  "No narrative sections.": "Belum ada bagian narasi.",
  "This version is read-only.": "Versi ini hanya dapat dibaca.",
  "Private download link available briefly for this published version.":
    "Tautan unduhan privat tersedia sementara untuk versi yang diterbitkan ini.",
  "No subject narrative.": "Belum ada narasi mata pelajaran.",
  "No published result": "Belum ada hasil yang diterbitkan",
  "Published · Version ": "Diterbitkan · Versi ",
  "Viewing child": "Melihat data anak",
  Primary: "Utama",
  School: "Sekolah",
  Grade: "Jenjang",
  Enrollment: "Pendaftaran",
  Session: "Sesi",
  "No result": "Belum ada hasil",
  "PDF not available yet.": "PDF belum tersedia.",
  "This report card changed in another session. Reload the latest version before continuing.":
    "Rapor ini berubah di sesi lain. Muat ulang versi terbaru sebelum melanjutkan.",
  "We couldn't complete that report card action right now.":
    "Tindakan rapor belum dapat diselesaikan. Silakan coba lagi.",
  "PDF generation failed.": "Pembuatan PDF gagal.",
  "PDF regeneration failed.": "Pembuatan ulang PDF gagal.",
  "PDF generation failed. Please try again.": "Pembuatan PDF gagal. Silakan coba lagi.",
  "PDF regeneration failed. Please try again.": "Pembuatan ulang PDF gagal. Silakan coba lagi.",
  "Official PDF regenerated. The previous non-authoritative Storage object still needs orphan cleanup.":
    "PDF resmi berhasil dibuat ulang. Objek Storage lama yang tidak otoritatif masih perlu dibersihkan.",
  "Document status could not be retrieved. Please retry.":
    "Status dokumen tidak dapat diambil. Silakan coba lagi.",
  "The document could not be prepared. Please try again.":
    "Dokumen tidak dapat disiapkan. Silakan coba lagi.",
  Available: "Tersedia",
  "Generation failed": "Pembuatan gagal",
  "Not generated": "Belum dibuat",
  Generated: "Dibuat",
  "Generate once for this published version.": "Buat satu kali untuk versi yang diterbitkan ini.",
  "No new document can be generated for this lifecycle state.":
    "Dokumen baru tidak dapat dibuat pada tahap ini.",
  Updated: "Diperbarui",
  "Download PDF": "Unduh PDF",
  "Report Cards": "Rapor",
  "Report card": "Rapor",
  Schedule: "Jadwal",
  "Teaching Journal": "Jurnal Mengajar",
  Terms: "Semester",
  Term: "Semester",
  Code: "Kode",
  Name: "Nama",
  Starts: "Mulai",
  Ends: "Selesai",
  Status: "Status",
  State: "Status",
  Actions: "Tindakan",
  Stage: "Jenjang",
  Version: "Versi",
  Category: "Kategori",
  Capacity: "Kapasitas",
  Title: "Judul",
  Type: "Jenis",
  Dates: "Tanggal",
  Instruction: "Kegiatan belajar",
  Relationship: "Hubungan",
  Phone: "Telepon",
  Email: "Email",
  "Portal login": "Akses portal",
  "Invitation created.": "Undangan berhasil dibuat.",
  Expires: "Kedaluwarsa",
  Search: "Cari",
  "Search students": "Cari siswa",
  "All statuses": "Semua status",
  "All schools": "Semua sekolah",
  "All accessible students": "Semua siswa yang dapat diakses",
  "All grade levels": "Semua tingkat kelas",
  "All classrooms": "Semua rombongan belajar",
  "School filter": "Filter sekolah",
  "Not linked": "Belum tertaut",
  Linked: "Tertaut",
  Active: "Aktif",
  Inactive: "Tidak aktif",
  Draft: "Draf",
  Published: "Diterbitkan",
  Open: "Terbuka",
  Closed: "Ditutup",
  "No school selected": "Belum ada sekolah yang dipilih",
  "Select a school": "Pilih sekolah",
  "Select an organization": "Pilih organisasi",
  "No data.": "Belum ada data.",
  "No data": "Belum ada data",
  "Try again": "Coba lagi",
  Save: "Simpan",
  Cancel: "Batal",
  Close: "Tutup",
  Delete: "Hapus",
  "New academic year": "Tahun ajaran baru",
  "Edit academic year": "Ubah tahun ajaran",
  "New term": "Semester baru",
  "Edit term": "Ubah semester",
  "New grade level": "Tingkat kelas baru",
  "Edit grade level": "Ubah tingkat kelas",
  "New classroom": "Rombongan belajar baru",
  "Edit classroom": "Ubah rombongan belajar",
  "New subject": "Mata pelajaran baru",
  "Edit subject": "Ubah mata pelajaran",
  "New curriculum": "Kurikulum baru",
  "Edit curriculum": "Ubah kurikulum",
  "You do not have Finance visibility for the active school.":
    "Anda tidak memiliki akses ke keuangan sekolah aktif.",
  "Snapshot items": "Rincian snapshot",
  "New fee": "Biaya baru",
  Monthly: "Bulanan",
  "One-time": "Sekali bayar",
  Frequency: "Frekuensi",
  "Source fee": "Biaya sumber",
  "Version source fee": "Biaya sumber versi",
  "Select source fee": "Pilih biaya sumber",
  "Select fee": "Pilih biaya",
  "Select plan": "Pilih paket",
  "Select version": "Pilih versi",
  "Billing plan": "Paket tagihan",
  "Fees & billing plans": "Biaya dan paket tagihan",
  "No fees configured.": "Belum ada biaya yang diatur.",
  "No billing plans configured.": "Belum ada paket tagihan yang diatur.",
  "No invoices for this school or period.": "Tidak ada faktur untuk sekolah atau periode ini.",
  "No payments recorded.": "Belum ada pembayaran yang dicatat.",
  "No billing records for your children.": "Belum ada catatan tagihan untuk anak Anda.",
  "Target: school": "Sasaran: sekolah",
  "immutable snapshot": "snapshot yang tidak dapat diubah",
  "Bounded target rows:": "Baris sasaran yang dibatasi:",
  "Manage school fee definitions and immutable billing rule versions.":
    "Kelola definisi biaya sekolah dan versi aturan tagihan yang tidak dapat diubah.",
  "Create fee": "Buat biaya",
  "New billing plan": "Paket tagihan baru",
  "Create plan": "Buat paket",
  "Fee catalog": "Daftar biaya",
  "Billing plans": "Paket tagihan",
  "Stable plan identity": "Identitas paket tetap",
  "version(s)": "versi",
  "Create version": "Buat versi",
  school: "sekolah",
  "Billing generation": "Pembuatan tagihan",
  "Generate one bounded invoice from an immutable plan version.":
    "Buat satu faktur terukur dari versi paket yang tidak dapat diubah.",
  "Invoice detail": "Detail faktur",
  "Manual/offline payment history for the active school.":
    "Riwayat pembayaran manual atau luring untuk sekolah aktif.",
  "Read-only billing for children related to your account.":
    "Tagihan hanya-baca untuk anak yang terhubung dengan akun Anda.",
  "Immutable plan version": "Versi paket tetap",
  "Canonical StudentEnrollment ID": "ID pendaftaran siswa kanonis",
  "UUID from the bounded QA/approved roster": "UUID dari daftar QA yang disetujui",
  "Billing period": "Periode tagihan",
  "YYYY-MM or ONE_TIME": "YYYY-MM atau ONE_TIME",
  "Amount (IDR)": "Jumlah (IDR)",
  "Create invoice": "Buat faktur",
  "Generate invoice": "Buat faktur",
  "Issue invoice": "Terbitkan faktur",
  "Void invoice": "Batalkan faktur",
  "Reverse payment": "Balikkan pembayaran",
  "Fee archived": "Biaya diarsipkan",
  "Record payment": "Catat pembayaran",
  "Select academic context": "Pilih konteks akademik",
  "No learners match this filter": "Tidak ada siswa yang sesuai dengan filter ini",
  "Attendance Session": "Sesi presensi",
  "Open attendance session": "Buka sesi presensi",
  "Submit Attendance?": "Ajukan presensi?",
  "Lock Attendance?": "Kunci presensi?",
  "Choose a class": "Pilih kelas",
  "Choose classroom": "Pilih rombongan belajar",
  "Operational daily Attendance workspace and bounded history.":
    "Ruang kerja presensi harian dan riwayat terbatas.",
  "Batch draft editor for the immutable dated roster.":
    "Editor draf batch untuk daftar siswa bertanggal yang tidak dapat diubah.",
  "Daily workspace": "Ruang kerja harian",
  History: "Riwayat",
  "Open session": "Buka sesi",
  "Calendar event affects instruction": "Acara kalender memengaruhi kegiatan belajar",
  "Another Attendance context exists": "Konteks presensi lain sudah tersedia",
  "Another Attendance or timetable context exists for this classroom and date. This is advisory and may not be a duplicate.":
    "Konteks presensi atau jadwal lain tersedia untuk kelas dan tanggal ini. Informasi ini bersifat peringatan dan belum tentu duplikat.",
  "Record the work completed in scheduled teaching sessions.":
    "Catat kegiatan yang dilakukan dalam sesi mengajar terjadwal.",
  "Read-only visibility into teaching journals within your authorized school scope.":
    "Tampilan hanya-baca jurnal mengajar dalam lingkup sekolah yang diizinkan.",
  "Journal Monitor": "Monitor Jurnal",
  "Material taught": "Materi yang diajarkan",
  "Record manual payment": "Catat pembayaran manual",
  "Payment history": "Riwayat pembayaran",
  "Your children’s invoices": "Faktur anak Anda",
  "Plan code": "Kode paket",
  "Plan name": "Nama paket",
  "Permission Requests": "Permintaan Izin",
  "Staff workflow": "Alur kerja staf",
  Request: "Permintaan",
  Target: "Sasaran",
  Due: "Tenggat",
  Responses: "Respons",
  Action: "Tindakan",
  "Create permission request": "Buat permintaan izin",
  "Edit draft request": "Ubah draf permintaan",
  "Save a draft first, then publish it after reviewing its recipient snapshot.":
    "Simpan sebagai draf, lalu terbitkan setelah meninjau daftar penerima.",
  "Request type": "Jenis permintaan",
  "Response deadline": "Batas waktu respons",
  Description: "Deskripsi",
  "Target audience": "Target penerima",
  "Search title or type": "Cari judul atau jenis",
  "All request statuses": "Semua status permintaan",
  Admissions: "Penerimaan siswa",
  "PPDB workspace": "Ruang kerja PPDB",
  "Manage admission cycles and review applications within your active school.":
    "Kelola gelombang penerimaan dan tinjau pendaftaran di sekolah aktif.",
  "Admission cycles": "Gelombang penerimaan",
  "No cycles are available in this school.": "Belum ada gelombang penerimaan di sekolah ini.",
  "We could not load this admissions view": "Data penerimaan tidak dapat dimuat",
  "Review applications": "Tinjau pendaftaran",
  "Application queue": "Antrean pendaftaran",
  "New admission cycle": "Gelombang penerimaan baru",
  "Open cycle": "Buka gelombang",
  "Close cycle": "Tutup gelombang",
  "Reopen cycle": "Buka kembali gelombang",
  "Archive cycle": "Arsipkan gelombang",
  "SIS Imports": "Impor SIS",
  "SIS Export": "Ekspor SIS",
  "New Import": "Impor baru",
  "New SIS Import": "Impor SIS baru",
  "Upload, validate, review, and atomically commit canonical school data.":
    "Unggah, validasi, tinjau, lalu terapkan data sekolah secara atomik.",
  "One canonical .xlsx workbook imports data into one selected school.":
    "Satu berkas .xlsx standar mengimpor data ke satu sekolah yang dipilih.",
  "Import history": "Riwayat impor",
  "Authoritative jobs for the selected school.": "Proses resmi untuk sekolah terpilih.",
  File: "Berkas",
  Created: "Dibuat",
  Validated: "Divalidasi",
  Completed: "Selesai",
  Summary: "Ringkasan",
  View: "Lihat",
  "Select workbook": "Pilih buku kerja",
  "Upload unavailable": "Unggahan tidak tersedia",
  "XLSX workbook": "Buku kerja XLSX",
  "Invalid job": "Proses tidak valid",
  "The URL does not contain a valid job identifier.": "URL tidak memuat ID proses yang valid.",
  "Back to History": "Kembali ke riwayat",
  "Job unavailable": "Proses tidak tersedia",
  "Action required": "Tindakan diperlukan",
  "Workflow status": "Status alur kerja",
  "Import failed safely": "Impor gagal dengan aman",
  "Validation is processing. Refresh to obtain the authoritative state.":
    "Validasi sedang diproses. Muat ulang untuk melihat status terkini.",
  "Atomic import is in progress. No second execution will be started.":
    "Impor atomik sedang berjalan. Proses kedua tidak akan dimulai.",
  "Import completed": "Impor selesai",
  "The database committed the full plan atomically.":
    "Basis data menerapkan seluruh rencana secara atomik.",
  "This import is cancelled and cannot be confirmed.":
    "Impor ini dibatalkan dan tidak dapat dikonfirmasi.",
  "Confirmation authorization is not in memory": "Otorisasi konfirmasi tidak tersedia di sesi ini",
  "Validated rows": "Baris tervalidasi",
  "Sheet / row": "Lembar / baris",
  Entity: "Entitas",
  Values: "Nilai",
  "Changes & issues": "Perubahan dan masalah",
  "Download Error Report": "Unduh laporan kesalahan",
  "Confirm Import": "Konfirmasi impor",
  "Commit this SIS import?": "Terapkan impor SIS ini?",
  "Durable reference readiness": "Kesiapan referensi permanen",
  "Prepare References": "Siapkan referensi",
  "Prepare durable SIS references?": "Siapkan referensi SIS permanen?",
  "Latest preparation result": "Hasil persiapan terbaru",
  "Export SIS Data": "Ekspor data SIS",
  "Download the canonical seven-sheet workbook for the selected school.":
    "Unduh buku kerja standar tujuh lembar untuk sekolah yang dipilih.",
  "You do not have access to this Finance action.":
    "Anda tidak memiliki akses untuk tindakan keuangan ini.",
  "This record changed since it was loaded. Refresh and try again.":
    "Data ini berubah setelah dimuat. Muat ulang lalu coba lagi.",
  "The payment exceeds the current outstanding balance.":
    "Jumlah pembayaran melebihi saldo tagihan yang tersisa.",
  "This billing period is closed and cannot accept a new charge.":
    "Periode tagihan ini telah ditutup dan tidak dapat menerima biaya baru.",
  "This request was already processed or conflicts with an earlier request.":
    "Permintaan ini sudah diproses atau bertentangan dengan permintaan sebelumnya.",
  "This Finance record is no longer in a valid state for that action.":
    "Data keuangan ini tidak lagi berada pada status yang sesuai untuk tindakan tersebut.",
  "Finance could not complete the request. Please try again.":
    "Permintaan keuangan tidak dapat diselesaikan. Silakan coba lagi.",
  "Student identity is held at organization level; school, grade and classroom come from enrolment.":
    "Identitas siswa dikelola di tingkat organisasi; sekolah, jenjang, dan rombongan belajar mengikuti pendaftaran.",
  "Guardians are organization-level people linked to students through family relationships.":
    "Orang tua/wali tercatat di tingkat organisasi dan dihubungkan ke siswa melalui hubungan keluarga.",
  "Staff identity belongs to the organization; working at a school is a separate assignment.":
    "Identitas staf tercatat di tingkat organisasi; penugasan ke sekolah dikelola terpisah.",
  "Contact details and related students.": "Informasi kontak dan siswa yang terkait.",
  "Enrolment history, classroom placements and guardian relationships.":
    "Riwayat pendaftaran, penempatan kelas, dan hubungan orang tua/wali.",
  "Organization-level staff identity with its school assignments.":
    "Identitas staf tingkat organisasi beserta penugasannya di sekolah.",
  "Student identity belongs to the organization. Enrolment into a school and academic year is managed on the student's profile.":
    "Identitas siswa tercatat di tingkat organisasi. Pendaftaran ke sekolah dan tahun ajaran dikelola melalui profil siswa.",
  "Guardian contact details. Student relationships are managed from a student's profile.":
    "Informasi kontak orang tua/wali. Hubungan dengan siswa dikelola dari profil siswa.",
  "School assignments are managed from the staff member's profile.":
    "Penugasan sekolah dikelola dari profil staf.",
  "Edit student": "Ubah data siswa",
  "Register student": "Daftarkan siswa",
  "Edit staff member": "Ubah data staf",
  "Add staff member": "Tambah staf",
  "Edit guardian": "Ubah data orang tua/wali",
  "Add guardian": "Tambah orang tua/wali",
  "Guardian profile": "Profil orang tua/wali",
  "Student profile": "Profil siswa",
  "Staff profile": "Profil staf",
};

const extendedSharedCopy: Record<string, string> = {
  "All statuses": "Semua status",
  "No applications match this filter.": "Tidak ada pendaftaran yang sesuai dengan filter ini.",
  Previous: "Sebelumnya",
  Next: "Berikutnya",
  "Communication Center unavailable": "Pusat komunikasi tidak tersedia",
  "Communication Center is available to authorized school staff only.":
    "Pusat komunikasi hanya tersedia bagi staf sekolah yang berwenang.",
  "You are not authorized for this school workflow.":
    "Anda tidak memiliki akses untuk alur kerja sekolah ini.",
  "Choose a valid .xlsx file created from the latest template.":
    "Pilih berkas .xlsx valid yang dibuat dari templat terbaru.",
  "The workbook is larger than the 10 MB limit.": "Ukuran buku kerja melebihi batas 10 MB.",
  "The workbook is corrupt or failed the safety checks.":
    "Buku kerja rusak atau tidak lolos pemeriksaan keamanan.",
  "This import job was not found or is outside your access.":
    "Pekerjaan impor tidak ditemukan atau berada di luar akses Anda.",
  "The import state changed. Refresh before continuing.":
    "Status impor berubah. Muat ulang sebelum melanjutkan.",
  "Resolve every blocking workbook error before confirming.":
    "Selesaikan semua kesalahan buku kerja yang menghambat sebelum mengonfirmasi.",
  "Confirmation authorization expired. Revalidate the workbook.":
    "Otorisasi konfirmasi kedaluwarsa. Validasi ulang buku kerja.",
  "School data changed after validation. Revalidate before confirming.":
    "Data sekolah berubah setelah validasi. Validasi ulang sebelum mengonfirmasi.",
  "A durable reference changed after validation. Revalidate first.":
    "Referensi tetap berubah setelah validasi. Validasi ulang terlebih dahulu.",
  "A class placement now overlaps another placement. Revalidate first.":
    "Penempatan kelas kini bertumpang tindih dengan penempatan lain. Validasi ulang terlebih dahulu.",
  "Academic year, grade, or classroom data changed. Revalidate first.":
    "Data tahun ajaran, tingkat, atau kelas berubah. Validasi ulang terlebih dahulu.",
  "Prepare durable references before exporting.": "Siapkan referensi tetap sebelum mengekspor.",
  "The operation could not be completed safely.": "Operasi tidak dapat diselesaikan dengan aman.",
  "Workbook uploaded safely.": "Buku kerja berhasil diunggah dengan aman.",
  "Validation found issues.": "Validasi menemukan masalah.",
  "Workbook is ready for confirmation.": "Buku kerja siap dikonfirmasi.",
  "Durable references prepared.": "Referensi tetap berhasil disiapkan.",
  "Historical period — closed": "Periode historis — ditutup",
  "Historical period — archived": "Periode historis — diarsipkan",
  "Closed by an authorized school operator.": "Ditutup oleh petugas sekolah yang berwenang.",
  "Closure readiness": "Kesiapan penutupan",
  "Closing locks normal academic changes while historical records remain readable.":
    "Penutupan mengunci perubahan akademik biasa, sementara catatan historis tetap dapat dibaca.",
  "Refresh readiness": "Muat ulang kesiapan",
  "Checking authoritative readiness…": "Memeriksa kesiapan resmi…",
  "Readiness is unavailable. Refresh before attempting closure.":
    "Informasi kesiapan tidak tersedia. Muat ulang sebelum mencoba menutup periode.",
  "Ready for closure": "Siap ditutup",
  "closure blocker(s)": "kendala penutupan",
  "Warning:": "Peringatan:",
  "All required operational workflows are finalized.":
    "Semua alur kerja operasional wajib telah diselesaikan.",
  "Close Term": "Tutup semester",
  "Close Academic Year": "Tutup tahun ajaran",
  Close: "Tutup",
  "This makes the period historical and blocks normal schedule, attendance, assessment, score, enrollment, and report-card changes. Historical reads remain available. The server will recheck readiness before applying the close.":
    "Periode ini akan menjadi historis dan perubahan biasa pada jadwal, presensi, penilaian, nilai, pendaftaran, dan rapor akan dikunci. Data historis tetap dapat dibaca. Server akan memeriksa ulang kesiapan sebelum penutupan diterapkan.",
  "Confirm close": "Konfirmasi penutupan",
  "Period closure": "Penutupan periode",
  "Could not save draft": "Draf tidak dapat disimpan",
  "All terms": "Semua semester",
  "All request statuses": "Semua status permintaan",
  Request: "Permintaan",
  Draft: "Draf",
  Open: "Terbuka",
  Closed: "Ditutup",
  Cancelled: "Dibatalkan",
  "Find enrolled Students": "Cari siswa terdaftar",
  "Classroom target": "Target kelas",
  "Selected Students": "Siswa yang dipilih",
  "Target mode": "Mode target",
  Created: "Dibuat",
  Published: "Diterbitkan",
  Workflow: "Alur kerja",
  "Only valid actions for the current lifecycle and your permissions are shown.":
    "Hanya tindakan yang sesuai dengan siklus saat ini dan izin Anda yang ditampilkan.",
  "Recipient responses": "Respons penerima",
  Student: "Siswa",
  Decision: "Keputusan",
  "Decided at": "Diputuskan pada",
  "Current decision": "Keputusan saat ini",
  Deadline: "Batas waktu",
  "No decision history yet.": "Belum ada riwayat keputusan.",
  "Please try again. If the problem continues, contact your school administrator.":
    "Silakan coba lagi. Jika masalah berlanjut, hubungi administrator sekolah.",
  "Requests shared with your account will appear here.":
    "Permintaan yang dibagikan dengan akun Anda akan muncul di sini.",
  "No student details available": "Rincian siswa tidak tersedia",
  "Generate Report Card": "Buat rapor",
  "Search student": "Cari siswa",
  "Student enrollment": "Pendaftaran siswa",
  "Candidates could not be loaded": "Daftar kandidat tidak dapat dimuat",
  "No eligible student enrollments": "Tidak ada pendaftaran siswa yang memenuhi syarat",
  "Generation result is uncertain": "Hasil pembuatan belum dapat dipastikan",
  "Report card access unavailable": "Akses rapor tidak tersedia",
  "Select a school": "Pilih sekolah",
  "Choose a school to load its report cards.": "Pilih sekolah untuk memuat rapornya.",
  "Report cards could not be loaded": "Rapor tidak dapat dimuat",
  "No report cards found": "Rapor tidak ditemukan",
  "No snapshots match the current school and filters.":
    "Tidak ada snapshot yang cocok dengan sekolah dan filter saat ini.",
  Updated: "Diperbarui",
  "Attendance snapshot": "Snapshot presensi",
  "Frozen subject snapshot": "Snapshot mata pelajaran terkunci",
  "Final score": "Nilai akhir",
  Predicate: "Kriteria",
  "No subject snapshots": "Tidak ada snapshot mata pelajaran",
  "Narrative sections": "Bagian narasi",
  "No narrative sections.": "Belum ada bagian narasi.",
  "Add narrative section": "Tambah bagian narasi",
  "· viewing": "· melihat",
  "Workflow result is uncertain": "Hasil alur kerja belum dapat dipastikan",
  "Retry the same action to safely confirm its result.":
    "Ulangi tindakan yang sama untuk memastikan hasilnya dengan aman.",
  "Publish official Report Card?": "Terbitkan rapor resmi?",
  "Create a new draft version?": "Buat versi draf baru?",
  "This version is read-only.": "Versi ini hanya dapat dibaca.",
  "Document status unavailable": "Status dokumen tidak tersedia",
  "Regenerate official PDF?": "Buat ulang PDF resmi?",
  "Report card could not be loaded": "Rapor tidak dapat dimuat",
  "Report card not found": "Rapor tidak ditemukan",
  "This report card changed elsewhere": "Rapor ini telah berubah di tempat lain",
  "Reload the latest snapshot before saving again.":
    "Muat ulang snapshot terbaru sebelum menyimpan kembali.",
  "Save result is uncertain": "Hasil penyimpanan belum dapat dipastikan",
  "Your edits are being held. Retry the same save to confirm its result.":
    "Perubahan Anda masih disimpan sementara. Ulangi penyimpanan yang sama untuk memastikan hasilnya.",
  "This is a snapshot": "Ini adalah snapshot",
  "Subject snapshot": "Snapshot mata pelajaran",
  "Regenerate snapshot": "Buat ulang snapshot",
  "We could not load this admissions view": "Data penerimaan tidak dapat dimuat",
  "Application received": "Pendaftaran diterima",
  "Application details": "Rincian pendaftaran",
  "Fields marked required are needed to submit.":
    "Kolom bertanda wajib harus diisi untuk mengirim.",
  Applicant: "Calon siswa",
  "Full name *": "Nama lengkap *",
  "NISN (optional)": "NISN (opsional)",
  "Target grade *": "Tingkat kelas tujuan *",
  "Guardian / contact": "Orang tua/wali / kontak",
  "Relationship *": "Hubungan *",
  Consent: "Persetujuan",
  "Reason *": "Alasan *",
  "Choose a cycle to inspect its application queue.":
    "Pilih gelombang untuk melihat antrean pendaftarannya.",
  "Archived cycles are read-only.": "Gelombang yang diarsipkan hanya dapat dibaca.",
  Applications: "Pendaftaran",
  "Guardians / consent": "Orang tua/wali / persetujuan",
  "Stage history": "Riwayat tahapan",
  "Confirmed server transitions only.": "Hanya transisi yang dikonfirmasi server.",
  "Conversion summary": "Ringkasan konversi",
  "Converted to canonical SIS records.": "Dikonversi menjadi data SIS resmi.",
  "Classroom placement was not created.": "Penempatan kelas tidak dibuat.",
  "Convert accepted application?": "Konversi pendaftaran yang diterima?",
  "There are no invoices for this student.": "Tidak ada tagihan untuk siswa ini.",
  "No payments recorded.": "Belum ada pembayaran yang tercatat.",
  "Your current permissions do not include report-card access.":
    "Izin Anda saat ini tidak mencakup akses ke rapor.",
  "Your current school permissions do not include this bulk SIS workflow. Server authorization remains authoritative.":
    "Izin Anda di sekolah ini tidak mencakup alur kerja SIS massal. Otorisasi server tetap menjadi acuan.",
  "This period changed in another session. Reload the latest period before trying again.":
    "Periode ini berubah di sesi lain. Muat ulang periode terbaru sebelum mencoba lagi.",
  "Search permission requests": "Cari permintaan izin",
  "Filter request status": "Filter status permintaan",
  "This request changed. Reload the latest data before saving again.":
    "Permintaan ini berubah. Muat ulang data terbaru sebelum menyimpan kembali.",
  "No active recipients are eligible for this request.":
    "Tidak ada penerima aktif yang memenuhi syarat untuk permintaan ini.",
  "Only draft requests can be edited or published.":
    "Hanya draf yang dapat diubah atau diterbitkan.",
  "This request is not open for that action.":
    "Permintaan ini tidak terbuka untuk tindakan tersebut.",
  "The request deadline has passed.": "Batas waktu permintaan telah lewat.",
  "The student or classroom target is incomplete or invalid.":
    "Target siswa atau kelas belum lengkap atau tidak valid.",
  "You do not have permission to take this action.":
    "Anda tidak memiliki izin untuk melakukan tindakan ini.",
  "This action could not be completed. Try again.": "Tindakan tidak dapat diselesaikan. Coba lagi.",
  "Draft updated.": "Draf diperbarui.",
  "In-app reminder sent.": "Pengingat dalam aplikasi telah dikirim.",
  "Request published.": "Permintaan diterbitkan.",
  "Request closed.": "Permintaan ditutup.",
  "Request cancelled.": "Permintaan dibatalkan.",
  "This period still has items to resolve before it can be closed. Refresh readiness and review the checklist.":
    "Masih ada hal yang perlu diselesaikan sebelum periode ini dapat ditutup. Muat ulang kesiapan dan tinjau daftar periksa.",
  "You do not have permission to perform this period action.":
    "Anda tidak memiliki izin untuk melakukan tindakan pada periode ini.",
  "This period is no longer in a state that allows this action.":
    "Status periode ini tidak lagi memungkinkan tindakan tersebut.",
  "This request could not be confirmed. Start a new request after checking the period status.":
    "Permintaan ini tidak dapat dikonfirmasi. Periksa status periode sebelum memulai permintaan baru.",
  "Enter a reason with at least the required detail before reopening this period.":
    "Masukkan alasan dengan rincian yang diwajibkan sebelum membuka kembali periode ini.",
  "The academic period action could not be completed. Reload and try again.":
    "Tindakan periode akademik tidak dapat diselesaikan. Muat ulang dan coba lagi.",
  "Reopen period": "Buka kembali periode",
  "Reload latest period": "Muat ulang periode terbaru",
  "Retry same request": "Ulangi permintaan yang sama",
  "Start a new request": "Mulai permintaan baru",
  "Loading access context…": "Memuat konteks akses…",
  "You do not have permission to view student progression records.":
    "Anda tidak memiliki izin untuk melihat data kenaikan siswa.",
  "The progression operation could not be completed.":
    "Operasi kenaikan siswa tidak dapat diselesaikan.",
  "Loading progression batches…": "Memuat kelompok kenaikan siswa…",
  "No progression batches yet.": "Belum ada kelompok kenaikan siswa.",
  "Loading batch…": "Memuat kelompok…",
  "Bounded results recorded for this immutable batch.":
    "Hasil terbatas yang tercatat pada kelompok permanen ini.",
  "Source enrollment ·": "Pendaftaran asal ·",
  Outcome: "Hasil",
  "Ready information": "Informasi kesiapan",
  "Reload latest data": "Muat ulang data terbaru",
  "Access denied": "Akses ditolak",
  "Choose the school that owns this import or export.":
    "Pilih sekolah yang memiliki impor atau ekspor ini.",
  "Import history": "Riwayat impor",
  "Authoritative jobs for the selected school.": "Pekerjaan resmi untuk sekolah yang dipilih.",
  File: "Berkas",
  Validated: "Divalidasi",
  Completed: "Selesai",
  Summary: "Ringkasan",
  "Select workbook": "Pilih workbook",
  "Upload unavailable": "Pengunggahan tidak tersedia",
  "Invalid job": "Pekerjaan tidak valid",
  "The URL does not contain a valid job identifier.": "URL tidak memuat ID pekerjaan yang valid.",
  "Back to History": "Kembali ke riwayat",
  "Job unavailable": "Pekerjaan tidak tersedia",
  "Action required": "Tindakan diperlukan",
  "Workflow status": "Status alur kerja",
  "Import failed safely": "Impor gagal dengan aman",
  "Import completed": "Impor selesai",
  "Confirmation authorization is not in memory": "Otorisasi konfirmasi tidak tersimpan",
  "Validated rows": "Baris tervalidasi",
  "Sheet / row": "Lembar / baris",
  Entity: "Entitas",
  Values: "Nilai",
  "Changes & issues": "Perubahan & masalah",
  "Confirm Import": "Konfirmasi impor",
  "Commit this SIS import?": "Terapkan impor SIS ini?",
  "Export unavailable": "Ekspor tidak tersedia",
  "Durable reference readiness": "Kesiapan referensi permanen",
  "Readiness unavailable": "Kesiapan tidak tersedia",
  "Prepare durable SIS references?": "Siapkan referensi SIS permanen?",
  "Latest preparation result": "Hasil persiapan terbaru",
  "Progression batches": "Kelompok kenaikan kelas",
  "School-scoped annual rollover work.": "Proses kenaikan tahunan dalam lingkup sekolah.",
  "Source → target": "Asal → tujuan",
  Candidates: "Kandidat",
  Decided: "Diputuskan",
  Warnings: "Peringatan",
  "Create Progression Batch": "Buat kelompok kenaikan kelas",
  "Select source year": "Pilih tahun ajaran asal",
  "Select target year": "Pilih tahun ajaran tujuan",
  "Readiness warning": "Peringatan kesiapan",
  "Exception reason is required before this decision can be submitted.":
    "Alasan pengecualian wajib diisi sebelum keputusan ini dapat dikirim.",
  "Select outcome": "Pilih hasil",
  "Select grade": "Pilih tingkat kelas",
  "Select classroom": "Pilih kelas",
  "Applied result": "Hasil yang diterapkan",
  Promoted: "Naik kelas",
  Retained: "Tinggal kelas",
  Graduated: "Lulus",
  "Created target enrollments": "Pendaftaran tujuan dibuat",
  "Created target class placements": "Penempatan kelas tujuan dibuat",
  "Applied at": "Diterapkan pada",
  "Reference:": "Referensi:",
  "Status:": "Status:",
  "Submitted:": "Dikirim:",
  "Name:": "Nama:",
  Submitted: "Dikirim",
  Now: "Sekarang",
  "Not provided": "Tidak diberikan",
};

/** Translate exact shared UI labels only; values and domain identifiers are untouched. */
export function translateUiText(value: string, locale: Locale) {
  if (locale === "en") return value;
  const periodLabel = /^Period\s+(\d+)$/i.exec(value);
  if (periodLabel) return `Periode ${periodLabel[1]}`;
  const statusKey = `common.status.${value.toLowerCase()}`;
  if (statusKey in messages.id) return messages.id[statusKey as keyof typeof messages.id];
  return sharedCopy[value] ?? extendedSharedCopy[value] ?? value;
}

export function translateUiNode(node: ReactNode, locale: Locale): ReactNode {
  if (typeof node === "string") return translateUiText(node, locale);
  if (Array.isArray(node))
    return node.map((child, index) => {
      const translated = translateUiNode(child, locale);
      return isValidElement(translated) && translated.key === null
        ? cloneElement(translated, { key: `localized-copy-${index}` })
        : translated;
    });
  if (isValidElement<{ children?: ReactNode }>(node) && node.props.children !== undefined)
    return cloneElement(node, {
      children: translateUiNode(node.props.children, locale),
    });
  return node;
}

export function useOptionalAppPreferences() {
  return useContext(PreferencesContext);
}

function isLocale(value: string | null): value is Locale {
  return value === "id" || value === "en";
}

function isTheme(value: string | null): value is Theme {
  return value === "light" || value === "dark";
}

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("id");
  const [theme, setThemeState] = useState<Theme>("light");

  useEffect(() => {
    const storedLocale = window.localStorage.getItem(LOCALE_KEY);
    const storedTheme = window.localStorage.getItem(THEME_KEY);
    if (isLocale(storedLocale)) setLocaleState(storedLocale);
    if (isTheme(storedTheme)) setThemeState(storedTheme);
  }, []);

  useEffect(() => {
    window.localStorage.setItem(LOCALE_KEY, locale);
    document.documentElement.lang = locale === "id" ? "id" : "en";
  }, [locale]);

  useEffect(() => {
    window.localStorage.setItem(THEME_KEY, theme);
    document.documentElement.classList.toggle("dark", theme === "dark");
    document.documentElement.style.colorScheme = theme;
  }, [theme]);

  const value = useMemo<PreferencesContextValue>(() => {
    const language = locale === "id" ? "id-ID" : "en-US";
    return {
      locale,
      theme,
      setLocale: (next) => setLocaleState(next),
      setTheme: (next) => setThemeState(next),
      t: (key, values) => {
        const message = String(messages[locale][key] ?? messages.en[key] ?? key);
        return values
          ? Object.entries(values).reduce<string>(
              (result, [name, value]) => result.replaceAll(`{${name}}`, value),
              message,
            )
          : message;
      },
      formatDate: (value, options) =>
        new Intl.DateTimeFormat(language, options).format(new Date(value)),
      formatNumber: (value, options) => new Intl.NumberFormat(language, options).format(value),
    };
  }, [locale, theme]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("useAppPreferences must be used inside AppPreferencesProvider");
  return context;
}

export const appPreferenceKeys = { locale: LOCALE_KEY, theme: THEME_KEY } as const;

/** Format presentation values using the active document locale, safely during SSR. */
export function formatPreferredDate(
  value: string | number | Date,
  options?: Intl.DateTimeFormatOptions,
  locale?: Locale,
) {
  const activeLocale =
    locale ??
    (typeof document !== "undefined" && document.documentElement.lang === "en" ? "en" : "id");
  const language = activeLocale === "en" ? "en-US" : "id-ID";
  return new Intl.DateTimeFormat(language, options).format(new Date(value));
}

export function formatPreferredNumber(
  value: number,
  options?: Intl.NumberFormatOptions,
  locale?: Locale,
) {
  const activeLocale =
    locale ??
    (typeof document !== "undefined" && document.documentElement.lang === "en" ? "en" : "id");
  const language = activeLocale === "en" ? "en-US" : "id-ID";
  return new Intl.NumberFormat(language, options).format(value);
}
