import { describe,expect,test } from "bun:test";import {readFileSync} from "node:fs";
const server=readFileSync(new URL("./sis-import.server.ts",import.meta.url),"utf8");const sql=readFileSync(new URL("../../supabase/migrations/20260912150000_b10_sis_import_server_transport.sql",import.meta.url),"utf8");
describe("B10 Phase 3C import server contract",()=>{
 test("1. all public operations authenticate",()=>{for(const n of ["downloadSisImportTemplate","uploadSisImportFile","validateSisImport","getSisImportPreview","confirmSisImport","getSisImportJob","listSisImportJobs","downloadSisImportErrors","prepareSisImportReferences"]){const i=server.indexOf(`const ${n}=createServerFn`);expect(i).toBeGreaterThan(0);expect(server.slice(i,i+180)).toContain("requireSupabaseAuth");}});
 test("2. upload is FormData binary, not base64 JSON",()=>{expect(server).toContain("x as FormData");expect(server).toContain("file.arrayBuffer()");expect(server).not.toMatch(/base64|service_role|SUPABASE_SERVICE_ROLE_KEY/);});
 test("3. validate trust chain is complete",()=>{for(const x of ["inspectXlsxZip(bytes)","parseSisWorkbook(bytes)","buildSisValidationPlan","computeNormalizedPlanFingerprint","canonicalizePersistedValidationPlan","signSisImportPlanAttestation","persist_sis_import_validation"])expect(server).toContain(x);});
 test("4. validate accepts job only",()=>expect(server).toContain("const jobInput = z.object({ jobId: uuid }).strict()"));
 test("5. confirm sends exactly job and token",()=>{const i=server.indexOf('rpc("commit_sis_import_job"');const call=server.slice(i,i+180);expect(call).toContain("p_job_id:data.jobId");expect(call).toContain("p_confirmation_token:data.confirmationToken");expect(call).not.toMatch(/plan|rows|fingerprint|entity/);});
 test("6. direct entity-ref enumeration absent",()=>expect(server).not.toMatch(/from\(["']sis_import_entity_refs/));
 test("7. migration app RPCs harden ACL",()=>{for(const sig of ["register_sis_import_source_file(uuid,text,text,text,bigint)","get_sis_import_validation_snapshot(uuid,text[],text[],text[],text[],text[])","get_sis_import_job_payload(uuid)"]){expect(sql).toContain(`revoke all on function public.${sig} from public,anon,service_role`);}});
 test("8. storage policies bind exact job and caller",()=>{expect(sql).toContain("j.created_by_profile_id=auth.uid()");expect(sql).toContain("fa.object_path=name");expect(sql).not.toMatch(/bucket_id='sis-imports'\s*\)?\s*;/);});
 test("9. error download rebuilds the corrected canonical workbook from the private source",()=>{const i=server.indexOf("const downloadSisImportErrors=createServerFn");const handler=server.slice(i);expect(handler).toContain("newSisImportObjectPath");expect(handler).toContain("storage.from(SIS_IMPORT_BUCKET).download(objectPath)");expect(handler).toContain("parseSisWorkbook(bytes)");expect(handler).toContain("writeSisCorrectedTemplate(sheetsData,issues,sourceRowNumbers)");expect(handler).not.toContain("writeSisErrorReport(issues)");});
});
