import { describe, expect, test } from "bun:test";
import ExcelJS from "exceljs";
import { assertSisUploadEnvelope, inspectXlsxZip, newSisImportObjectPath, SisFileError } from "./sis-import.storage.server";
import { parseSisWorkbook } from "./sis-import.xlsx";

async function xlsx() { const w=new ExcelJS.Workbook();w.addWorksheet("Students").addRow(["student_ref"]);return new Uint8Array(await w.xlsx.writeBuffer()); }
function central(bytes){for(let i=0;i<bytes.length-4;i++)if(new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(i,true)===0x02014b50)return i;throw new Error("central");}
function centrals(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),d=new TextDecoder(),out=[];for(let i=0;i<bytes.length-46;i++)if(v.getUint32(i,true)===0x02014b50){const n=v.getUint16(i+28,true);out.push({at:i,name:d.decode(bytes.subarray(i+46,i+46+n)),length:n});}return out;}
function duplicateCentralName(bytes,fromName,toName){const entry=centrals(bytes).find((x)=>x.name===fromName);if(!entry||toName.length>entry.length)throw new Error("entry");const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),extra=v.getUint16(entry.at+30,true);bytes.set(new TextEncoder().encode(toName),entry.at+46);v.setUint16(entry.at+28,toName.length,true);v.setUint16(entry.at+30,extra+entry.length-toName.length,true);}
async function errorCode(fn){try{await fn();return "none";}catch(e){return e instanceof SisFileError?e.code:"other";}}

describe("B10 upload and ZIP safety",()=>{
 test("1. valid XLSX passes bounded preflight",async()=>expect((await inspectXlsxZip(await xlsx())).entryCount).toBeGreaterThan(0));
 test("2. over 10MB envelope rejected",async()=>expect(await errorCode(()=>assertSisUploadEnvelope({name:"a.xlsx",size:10*1024*1024+1}))).toBe("B10_FILE_TOO_LARGE"));
 test("3. wrong extension rejected",async()=>expect(await errorCode(()=>assertSisUploadEnvelope({name:"a.xls",size:5}))).toBe("B10_FILE_INVALID"));
 test("4. wrong signature rejected",async()=>expect(await errorCode(()=>inspectXlsxZip(new Uint8Array(30)))).toBe("B10_FILE_CORRUPT_OR_UNSAFE"));
 test("5. corrupt ZIP rejected",async()=>expect(await errorCode(()=>inspectXlsxZip(Uint8Array.from([0x50,0x4b,...new Array(30).fill(0)])))).toBe("B10_FILE_CORRUPT_OR_UNSAFE"));
 test("6. path traversal entry rejected",async()=>{const b=await xlsx();const p=central(b);b.set(new TextEncoder().encode("../evil.xml"),p+46);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("7. encrypted entry rejected",async()=>{const b=await xlsx();const p=central(b);new DataView(b.buffer,b.byteOffset,b.byteLength).setUint16(p+8,1,true);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("8. too many entries rejected",async()=>{const b=await xlsx();expect(await errorCode(()=>inspectXlsxZip(b,{maxEntries:1,maxSingleUncompressed:32*1024*1024,maxTotalUncompressed:96*1024*1024}))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("9. actual emitted bytes enforce single-entry limit despite forged smaller declaration",async()=>{const b=await xlsx();const p=central(b);new DataView(b.buffer,b.byteOffset,b.byteLength).setUint32(p+24,1,true);expect(await errorCode(()=>inspectXlsxZip(b,{maxEntries:256,maxSingleUncompressed:8,maxTotalUncompressed:96*1024*1024}))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("10. forged larger compressed-size denominator cannot weaken actual output bounds",async()=>{const b=await xlsx();const p=central(b),v=new DataView(b.buffer,b.byteOffset,b.byteLength);v.setUint32(p+20,Math.min(b.length,v.getUint32(p+20,true)+128),true);expect(await errorCode(()=>inspectXlsxZip(b,{maxEntries:256,maxSingleUncompressed:8,maxTotalUncompressed:96*1024*1024}))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("11. deterministic storage path ignores filename authority",()=>{const id="11111111-1111-4111-8111-111111111111";const p=newSisImportObjectPath({organizationId:id,schoolId:id,jobId:id});expect(p).toBe(`${id}/${id}/sis-imports/${id}/source.xlsx`);expect(p).not.toContain("evil");});
 test("12. actual total emitted bytes are bounded",async()=>{const b=await xlsx();expect(await errorCode(()=>inspectXlsxZip(b,{maxEntries:256,maxSingleUncompressed:32*1024*1024,maxTotalUncompressed:16}))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("13. formula reaches parser only after preflight and is rejected",async()=>{const w=new ExcelJS.Workbook();for(const name of ["Staff","Students","Guardians","StaffSchoolAssignments","StudentGuardians","StudentEnrollments","ClassEnrollments"]){const s=w.addWorksheet(name);s.addRow(name==="Students"?["student_ref","nisn","full_name","preferred_name","gender","birth_date","birth_place","status"]:["x"]);if(name==="Students")s.addRow(["STU-1","1",{formula:"1+1",result:2}]);}const b=new Uint8Array(await w.xlsx.writeBuffer());await inspectXlsxZip(b);const parsed=await parseSisWorkbook(b);expect(parsed.issues.some((i)=>i.code==="B10_FORMULA_CELL_NOT_ALLOWED")).toBe(true);});
 test("14. backslash traversal is rejected",async()=>{const b=await xlsx(),p=central(b);b.set(new TextEncoder().encode("..\\evil.xml"),p+46);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("15. absolute and drive-prefixed paths are rejected",async()=>{for(const name of ["/evil.xml","C:evil.xml"]){const b=await xlsx(),p=central(b);b.set(new TextEncoder().encode(name),p+46);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");}});
 test("16. duplicate normalized entry names are rejected",async()=>{const b=await xlsx(),entries=centrals(b);let pair;for(const a of entries)for(const c of entries)if(a!==c&&a.length===c.length){pair=[a,c];break;}const [a,c]=pair;b.set(b.slice(a.at+46,a.at+46+a.length),c.at+46);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("17. truncated ZIP is rejected",async()=>{const b=await xlsx();expect(await errorCode(()=>inspectXlsxZip(b.slice(0,b.length-10)))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("18. duplicate [Content_Types].xml is rejected",async()=>{const b=await xlsx();duplicateCentralName(b,"xl/theme/theme1.xml","[Content_Types].xml");expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("19. duplicate xl/workbook.xml is rejected",async()=>{const b=await xlsx();duplicateCentralName(b,"docProps/core.xml","xl/workbook.xml");expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("20. missing required XLSX core part is rejected",async()=>{const b=await xlsx();duplicateCentralName(b,"[Content_Types].xml","xl/theme/theme1.xml");expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
 test("21. unsupported ZIP64 size sentinel without a valid extension is rejected",async()=>{const b=await xlsx(),p=central(b),v=new DataView(b.buffer,b.byteOffset,b.byteLength);v.setUint32(p+20,0xffffffff,true);v.setUint32(p+24,0xffffffff,true);expect(await errorCode(()=>inspectXlsxZip(b))).toBe("B10_FILE_CORRUPT_OR_UNSAFE");});
});
