/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccessPendingRouteImport } from './routes/_authenticated/access-pending'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSelectOrganizationRouteImport } from './routes/_authenticated/select-organization'
import { Route as AuthenticatedSelectSchoolRouteImport } from './routes/_authenticated/select-school'
import { Route as AuthenticatedAcademicCalendarRouteImport } from './routes/_authenticated/academic/calendar'
import { Route as AuthenticatedAcademicClassroomsRouteImport } from './routes/_authenticated/academic/classrooms'
import { Route as AuthenticatedAcademicCurriculaRouteImport } from './routes/_authenticated/academic/curricula'
import { Route as AuthenticatedAcademicGradeLevelsRouteImport } from './routes/_authenticated/academic/grade-levels'
import { Route as AuthenticatedAcademicSubjectsRouteImport } from './routes/_authenticated/academic/subjects'
import { Route as AuthenticatedAcademicTermsRouteImport } from './routes/_authenticated/academic/terms'
import { Route as AuthenticatedAcademicYearsRouteImport } from './routes/_authenticated/academic/years'
import { Route as AuthenticatedGuardiansIndexRouteImport } from './routes/_authenticated/guardians/index'
import { Route as AuthenticatedGuardiansGuardianIdRouteImport } from './routes/_authenticated/guardians/$guardianId'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'
import { Route as AuthenticatedTeachingAssignmentsIndexRouteImport } from './routes/_authenticated/teaching-assignments/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessPendingRoute =
  AuthenticatedAccessPendingRouteImport.update({
    id: '/access-pending',
    path: '/access-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelectOrganizationRoute =
  AuthenticatedSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelectSchoolRoute =
  AuthenticatedSelectSchoolRouteImport.update({
    id: '/select-school',
    path: '/select-school',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicCalendarRoute =
  AuthenticatedAcademicCalendarRouteImport.update({
    id: '/academic/calendar',
    path: '/academic/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicClassroomsRoute =
  AuthenticatedAcademicClassroomsRouteImport.update({
    id: '/academic/classrooms',
    path: '/academic/classrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicCurriculaRoute =
  AuthenticatedAcademicCurriculaRouteImport.update({
    id: '/academic/curricula',
    path: '/academic/curricula',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicGradeLevelsRoute =
  AuthenticatedAcademicGradeLevelsRouteImport.update({
    id: '/academic/grade-levels',
    path: '/academic/grade-levels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicSubjectsRoute =
  AuthenticatedAcademicSubjectsRouteImport.update({
    id: '/academic/subjects',
    path: '/academic/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicTermsRoute =
  AuthenticatedAcademicTermsRouteImport.update({
    id: '/academic/terms',
    path: '/academic/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic/years',
    path: '/academic/years',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuardiansIndexRoute =
  AuthenticatedGuardiansIndexRouteImport.update({
    id: '/guardians/',
    path: '/guardians/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuardiansGuardianIdRoute =
  AuthenticatedGuardiansGuardianIdRouteImport.update({
    id: '/guardians/$guardianId',
    path: '/guardians/$guardianId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachingAssignmentsIndexRoute =
  AuthenticatedTeachingAssignmentsIndexRouteImport.update({
    id: '/teaching-assignments/',
    path: '/teaching-assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-pending': typeof AuthenticatedAccessPendingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/select-school': typeof AuthenticatedSelectSchoolRoute
  '/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/guardians/': typeof AuthenticatedGuardiansIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teaching-assignments/': typeof AuthenticatedTeachingAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-pending': typeof AuthenticatedAccessPendingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/select-school': typeof AuthenticatedSelectSchoolRoute
  '/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/guardians': typeof AuthenticatedGuardiansIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/access-pending': typeof AuthenticatedAccessPendingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/_authenticated/select-school': typeof AuthenticatedSelectSchoolRoute
  '/_authenticated/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/_authenticated/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/_authenticated/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/_authenticated/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/_authenticated/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/_authenticated/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/_authenticated/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/_authenticated/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/guardians/': typeof AuthenticatedGuardiansIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teaching-assignments/': typeof AuthenticatedTeachingAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/access-pending'
    | '/dashboard'
    | '/select-organization'
    | '/select-school'
    | '/academic/calendar'
    | '/academic/classrooms'
    | '/academic/curricula'
    | '/academic/grade-levels'
    | '/academic/subjects'
    | '/academic/terms'
    | '/academic/years'
    | '/guardians/$guardianId'
    | '/staff/$staffId'
    | '/students/$studentId'
    | '/guardians/'
    | '/staff/'
    | '/students/'
    | '/teaching-assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/access-pending'
    | '/dashboard'
    | '/select-organization'
    | '/select-school'
    | '/academic/calendar'
    | '/academic/classrooms'
    | '/academic/curricula'
    | '/academic/grade-levels'
    | '/academic/subjects'
    | '/academic/terms'
    | '/academic/years'
    | '/guardians/$guardianId'
    | '/staff/$staffId'
    | '/students/$studentId'
    | '/guardians'
    | '/staff'
    | '/students'
    | '/teaching-assignments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/_authenticated/access-pending'
    | '/_authenticated/dashboard'
    | '/_authenticated/select-organization'
    | '/_authenticated/select-school'
    | '/_authenticated/academic/calendar'
    | '/_authenticated/academic/classrooms'
    | '/_authenticated/academic/curricula'
    | '/_authenticated/academic/grade-levels'
    | '/_authenticated/academic/subjects'
    | '/_authenticated/academic/terms'
    | '/_authenticated/academic/years'
    | '/_authenticated/guardians/$guardianId'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/guardians/'
    | '/_authenticated/staff/'
    | '/_authenticated/students/'
    | '/_authenticated/teaching-assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthzRoute: typeof HealthzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-pending': {
      id: '/_authenticated/access-pending'
      path: '/access-pending'
      fullPath: '/access-pending'
      preLoaderRoute: typeof AuthenticatedAccessPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-organization': {
      id: '/_authenticated/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof AuthenticatedSelectOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-school': {
      id: '/_authenticated/select-school'
      path: '/select-school'
      fullPath: '/select-school'
      preLoaderRoute: typeof AuthenticatedSelectSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/calendar': {
      id: '/_authenticated/academic/calendar'
      path: '/academic/calendar'
      fullPath: '/academic/calendar'
      preLoaderRoute: typeof AuthenticatedAcademicCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/classrooms': {
      id: '/_authenticated/academic/classrooms'
      path: '/academic/classrooms'
      fullPath: '/academic/classrooms'
      preLoaderRoute: typeof AuthenticatedAcademicClassroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/curricula': {
      id: '/_authenticated/academic/curricula'
      path: '/academic/curricula'
      fullPath: '/academic/curricula'
      preLoaderRoute: typeof AuthenticatedAcademicCurriculaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/grade-levels': {
      id: '/_authenticated/academic/grade-levels'
      path: '/academic/grade-levels'
      fullPath: '/academic/grade-levels'
      preLoaderRoute: typeof AuthenticatedAcademicGradeLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/subjects': {
      id: '/_authenticated/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AuthenticatedAcademicSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/terms': {
      id: '/_authenticated/academic/terms'
      path: '/academic/terms'
      fullPath: '/academic/terms'
      preLoaderRoute: typeof AuthenticatedAcademicTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/years': {
      id: '/_authenticated/academic/years'
      path: '/academic/years'
      fullPath: '/academic/years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians/': {
      id: '/_authenticated/guardians/'
      path: '/guardians'
      fullPath: '/guardians/'
      preLoaderRoute: typeof AuthenticatedGuardiansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians/$guardianId': {
      id: '/_authenticated/guardians/$guardianId'
      path: '/guardians/$guardianId'
      fullPath: '/guardians/$guardianId'
      preLoaderRoute: typeof AuthenticatedGuardiansGuardianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teaching-assignments/': {
      id: '/_authenticated/teaching-assignments/'
      path: '/teaching-assignments'
      fullPath: '/teaching-assignments/'
      preLoaderRoute: typeof AuthenticatedTeachingAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessPendingRoute: typeof AuthenticatedAccessPendingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSelectOrganizationRoute: typeof AuthenticatedSelectOrganizationRoute
  AuthenticatedSelectSchoolRoute: typeof AuthenticatedSelectSchoolRoute
  AuthenticatedAcademicCalendarRoute: typeof AuthenticatedAcademicCalendarRoute
  AuthenticatedAcademicClassroomsRoute: typeof AuthenticatedAcademicClassroomsRoute
  AuthenticatedAcademicCurriculaRoute: typeof AuthenticatedAcademicCurriculaRoute
  AuthenticatedAcademicGradeLevelsRoute: typeof AuthenticatedAcademicGradeLevelsRoute
  AuthenticatedAcademicSubjectsRoute: typeof AuthenticatedAcademicSubjectsRoute
  AuthenticatedAcademicTermsRoute: typeof AuthenticatedAcademicTermsRoute
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRoute
  AuthenticatedGuardiansGuardianIdRoute: typeof AuthenticatedGuardiansGuardianIdRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedGuardiansIndexRoute: typeof AuthenticatedGuardiansIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachingAssignmentsIndexRoute: typeof AuthenticatedTeachingAssignmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessPendingRoute: AuthenticatedAccessPendingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSelectOrganizationRoute: AuthenticatedSelectOrganizationRoute,
  AuthenticatedSelectSchoolRoute: AuthenticatedSelectSchoolRoute,
  AuthenticatedAcademicCalendarRoute: AuthenticatedAcademicCalendarRoute,
  AuthenticatedAcademicClassroomsRoute: AuthenticatedAcademicClassroomsRoute,
  AuthenticatedAcademicCurriculaRoute: AuthenticatedAcademicCurriculaRoute,
  AuthenticatedAcademicGradeLevelsRoute: AuthenticatedAcademicGradeLevelsRoute,
  AuthenticatedAcademicSubjectsRoute: AuthenticatedAcademicSubjectsRoute,
  AuthenticatedAcademicTermsRoute: AuthenticatedAcademicTermsRoute,
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRoute,
  AuthenticatedGuardiansGuardianIdRoute: AuthenticatedGuardiansGuardianIdRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedGuardiansIndexRoute: AuthenticatedGuardiansIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachingAssignmentsIndexRoute:
    AuthenticatedTeachingAssignmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthzRoute: HealthzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
