/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccessPendingRouteImport } from './routes/_authenticated/access-pending'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSelectOrganizationRouteImport } from './routes/_authenticated/select-organization'
import { Route as AuthenticatedSelectSchoolRouteImport } from './routes/_authenticated/select-school'
import { Route as AuthenticatedSisExportRouteImport } from './routes/_authenticated/sis-export'
import { Route as AuthenticatedAcademicCalendarRouteImport } from './routes/_authenticated/academic/calendar'
import { Route as AuthenticatedAcademicClassroomsRouteImport } from './routes/_authenticated/academic/classrooms'
import { Route as AuthenticatedAcademicCurriculaRouteImport } from './routes/_authenticated/academic/curricula'
import { Route as AuthenticatedAcademicGradeLevelsRouteImport } from './routes/_authenticated/academic/grade-levels'
import { Route as AuthenticatedAcademicSubjectsRouteImport } from './routes/_authenticated/academic/subjects'
import { Route as AuthenticatedAcademicTermsRouteImport } from './routes/_authenticated/academic/terms'
import { Route as AuthenticatedAcademicYearsRouteImport } from './routes/_authenticated/academic/years'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments/index'
import { Route as AuthenticatedAssessmentsIdRouteImport } from './routes/_authenticated/assessments/$id'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedGuardiansIndexRouteImport } from './routes/_authenticated/guardians/index'
import { Route as AuthenticatedGuardiansGuardianIdRouteImport } from './routes/_authenticated/guardians/$guardianId'
import { Route as AuthenticatedPermissionRequestsIndexRouteImport } from './routes/_authenticated/permission-requests/index'
import { Route as AuthenticatedPermissionRequestsRequestIdRouteImport } from './routes/_authenticated/permission-requests/$requestId'
import { Route as AuthenticatedPermissionRequestsNewRouteImport } from './routes/_authenticated/permission-requests/new'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalAttendanceRouteImport } from './routes/_authenticated/portal/attendance'
import { Route as AuthenticatedPortalPermissionRequestsRouteImport } from './routes/_authenticated/portal/permission-requests'
import { Route as AuthenticatedPortalReportCardsRouteImport } from './routes/_authenticated/portal/report-cards'
import { Route as AuthenticatedPortalScheduleRouteImport } from './routes/_authenticated/portal/schedule'
import { Route as AuthenticatedPortalScoresRouteImport } from './routes/_authenticated/portal/scores'
import { Route as AuthenticatedReportCardsIndexRouteImport } from './routes/_authenticated/report-cards/index'
import { Route as AuthenticatedReportCardsIdRouteImport } from './routes/_authenticated/report-cards/$id'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated/schedule/index'
import { Route as AuthenticatedScheduleMyRouteImport } from './routes/_authenticated/schedule/my'
import { Route as AuthenticatedSisImportsIndexRouteImport } from './routes/_authenticated/sis-imports/index'
import { Route as AuthenticatedSisImportsJobIdRouteImport } from './routes/_authenticated/sis-imports/$jobId'
import { Route as AuthenticatedSisImportsNewRouteImport } from './routes/_authenticated/sis-imports/new'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedStudentAttendanceRouteImport } from './routes/_authenticated/student/attendance'
import { Route as AuthenticatedStudentReportCardsRouteImport } from './routes/_authenticated/student/report-cards'
import { Route as AuthenticatedStudentScheduleRouteImport } from './routes/_authenticated/student/schedule'
import { Route as AuthenticatedStudentScoresRouteImport } from './routes/_authenticated/student/scores'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'
import { Route as AuthenticatedTeachingAssignmentsIndexRouteImport } from './routes/_authenticated/teaching-assignments/index'
import { Route as AuthenticatedAttendanceSessionIdRouteImport } from './routes/_authenticated/attendance/session/$id'
import { Route as AuthenticatedPermissionRequestsRequestIdEditRouteImport } from './routes/_authenticated/permission-requests/$requestId.edit'
import { Route as AuthenticatedPortalPermissionRequestsRequestIdRouteImport } from './routes/_authenticated/portal/permission-requests/$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessPendingRoute =
  AuthenticatedAccessPendingRouteImport.update({
    id: '/access-pending',
    path: '/access-pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelectOrganizationRoute =
  AuthenticatedSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelectSchoolRoute =
  AuthenticatedSelectSchoolRouteImport.update({
    id: '/select-school',
    path: '/select-school',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSisExportRoute = AuthenticatedSisExportRouteImport.update({
  id: '/sis-export',
  path: '/sis-export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicCalendarRoute =
  AuthenticatedAcademicCalendarRouteImport.update({
    id: '/academic/calendar',
    path: '/academic/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicClassroomsRoute =
  AuthenticatedAcademicClassroomsRouteImport.update({
    id: '/academic/classrooms',
    path: '/academic/classrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicCurriculaRoute =
  AuthenticatedAcademicCurriculaRouteImport.update({
    id: '/academic/curricula',
    path: '/academic/curricula',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicGradeLevelsRoute =
  AuthenticatedAcademicGradeLevelsRouteImport.update({
    id: '/academic/grade-levels',
    path: '/academic/grade-levels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicSubjectsRoute =
  AuthenticatedAcademicSubjectsRouteImport.update({
    id: '/academic/subjects',
    path: '/academic/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicTermsRoute =
  AuthenticatedAcademicTermsRouteImport.update({
    id: '/academic/terms',
    path: '/academic/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic/years',
    path: '/academic/years',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIdRoute =
  AuthenticatedAssessmentsIdRouteImport.update({
    id: '/assessments/$id',
    path: '/assessments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuardiansIndexRoute =
  AuthenticatedGuardiansIndexRouteImport.update({
    id: '/guardians/',
    path: '/guardians/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuardiansGuardianIdRoute =
  AuthenticatedGuardiansGuardianIdRouteImport.update({
    id: '/guardians/$guardianId',
    path: '/guardians/$guardianId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionRequestsIndexRoute =
  AuthenticatedPermissionRequestsIndexRouteImport.update({
    id: '/permission-requests/',
    path: '/permission-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionRequestsRequestIdRoute =
  AuthenticatedPermissionRequestsRequestIdRouteImport.update({
    id: '/permission-requests/$requestId',
    path: '/permission-requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionRequestsNewRoute =
  AuthenticatedPermissionRequestsNewRouteImport.update({
    id: '/permission-requests/new',
    path: '/permission-requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAttendanceRoute =
  AuthenticatedPortalAttendanceRouteImport.update({
    id: '/portal/attendance',
    path: '/portal/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPermissionRequestsRoute =
  AuthenticatedPortalPermissionRequestsRouteImport.update({
    id: '/portal/permission-requests',
    path: '/portal/permission-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalReportCardsRoute =
  AuthenticatedPortalReportCardsRouteImport.update({
    id: '/portal/report-cards',
    path: '/portal/report-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalScheduleRoute =
  AuthenticatedPortalScheduleRouteImport.update({
    id: '/portal/schedule',
    path: '/portal/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalScoresRoute =
  AuthenticatedPortalScoresRouteImport.update({
    id: '/portal/scores',
    path: '/portal/scores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportCardsIndexRoute =
  AuthenticatedReportCardsIndexRouteImport.update({
    id: '/report-cards/',
    path: '/report-cards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportCardsIdRoute =
  AuthenticatedReportCardsIdRouteImport.update({
    id: '/report-cards/$id',
    path: '/report-cards/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleMyRoute = AuthenticatedScheduleMyRouteImport.update({
  id: '/schedule/my',
  path: '/schedule/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSisImportsIndexRoute =
  AuthenticatedSisImportsIndexRouteImport.update({
    id: '/sis-imports/',
    path: '/sis-imports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSisImportsJobIdRoute =
  AuthenticatedSisImportsJobIdRouteImport.update({
    id: '/sis-imports/$jobId',
    path: '/sis-imports/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSisImportsNewRoute =
  AuthenticatedSisImportsNewRouteImport.update({
    id: '/sis-imports/new',
    path: '/sis-imports/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAttendanceRoute =
  AuthenticatedStudentAttendanceRouteImport.update({
    id: '/student/attendance',
    path: '/student/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentReportCardsRoute =
  AuthenticatedStudentReportCardsRouteImport.update({
    id: '/student/report-cards',
    path: '/student/report-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentScheduleRoute =
  AuthenticatedStudentScheduleRouteImport.update({
    id: '/student/schedule',
    path: '/student/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentScoresRoute =
  AuthenticatedStudentScoresRouteImport.update({
    id: '/student/scores',
    path: '/student/scores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachingAssignmentsIndexRoute =
  AuthenticatedTeachingAssignmentsIndexRouteImport.update({
    id: '/teaching-assignments/',
    path: '/teaching-assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceSessionIdRoute =
  AuthenticatedAttendanceSessionIdRouteImport.update({
    id: '/attendance/session/$id',
    path: '/attendance/session/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionRequestsRequestIdEditRoute =
  AuthenticatedPermissionRequestsRequestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPermissionRequestsRequestIdRoute,
  } as any)
const AuthenticatedPortalPermissionRequestsRequestIdRoute =
  AuthenticatedPortalPermissionRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedPortalPermissionRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-pending': typeof AuthenticatedAccessPendingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/select-school': typeof AuthenticatedSelectSchoolRoute
  '/sis-export': typeof AuthenticatedSisExportRoute
  '/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/permission-requests/$requestId': typeof AuthenticatedPermissionRequestsRequestIdRouteWithChildren
  '/permission-requests/new': typeof AuthenticatedPermissionRequestsNewRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/permission-requests': typeof AuthenticatedPortalPermissionRequestsRouteWithChildren
  '/portal/report-cards': typeof AuthenticatedPortalReportCardsRoute
  '/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/portal/scores': typeof AuthenticatedPortalScoresRoute
  '/report-cards/$id': typeof AuthenticatedReportCardsIdRoute
  '/schedule/my': typeof AuthenticatedScheduleMyRoute
  '/sis-imports/$jobId': typeof AuthenticatedSisImportsJobIdRoute
  '/sis-imports/new': typeof AuthenticatedSisImportsNewRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/report-cards': typeof AuthenticatedStudentReportCardsRoute
  '/student/schedule': typeof AuthenticatedStudentScheduleRoute
  '/student/scores': typeof AuthenticatedStudentScoresRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/guardians/': typeof AuthenticatedGuardiansIndexRoute
  '/permission-requests/': typeof AuthenticatedPermissionRequestsIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/report-cards/': typeof AuthenticatedReportCardsIndexRoute
  '/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/sis-imports/': typeof AuthenticatedSisImportsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teaching-assignments/': typeof AuthenticatedTeachingAssignmentsIndexRoute
  '/attendance/session/$id': typeof AuthenticatedAttendanceSessionIdRoute
  '/permission-requests/$requestId/edit': typeof AuthenticatedPermissionRequestsRequestIdEditRoute
  '/portal/permission-requests/$requestId': typeof AuthenticatedPortalPermissionRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/access-pending': typeof AuthenticatedAccessPendingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/select-school': typeof AuthenticatedSelectSchoolRoute
  '/sis-export': typeof AuthenticatedSisExportRoute
  '/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/permission-requests/$requestId': typeof AuthenticatedPermissionRequestsRequestIdRouteWithChildren
  '/permission-requests/new': typeof AuthenticatedPermissionRequestsNewRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/permission-requests': typeof AuthenticatedPortalPermissionRequestsRouteWithChildren
  '/portal/report-cards': typeof AuthenticatedPortalReportCardsRoute
  '/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/portal/scores': typeof AuthenticatedPortalScoresRoute
  '/report-cards/$id': typeof AuthenticatedReportCardsIdRoute
  '/schedule/my': typeof AuthenticatedScheduleMyRoute
  '/sis-imports/$jobId': typeof AuthenticatedSisImportsJobIdRoute
  '/sis-imports/new': typeof AuthenticatedSisImportsNewRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student/report-cards': typeof AuthenticatedStudentReportCardsRoute
  '/student/schedule': typeof AuthenticatedStudentScheduleRoute
  '/student/scores': typeof AuthenticatedStudentScoresRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/guardians': typeof AuthenticatedGuardiansIndexRoute
  '/permission-requests': typeof AuthenticatedPermissionRequestsIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/report-cards': typeof AuthenticatedReportCardsIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/sis-imports': typeof AuthenticatedSisImportsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teaching-assignments': typeof AuthenticatedTeachingAssignmentsIndexRoute
  '/attendance/session/$id': typeof AuthenticatedAttendanceSessionIdRoute
  '/permission-requests/$requestId/edit': typeof AuthenticatedPermissionRequestsRequestIdEditRoute
  '/portal/permission-requests/$requestId': typeof AuthenticatedPortalPermissionRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/access-pending': typeof AuthenticatedAccessPendingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/_authenticated/select-school': typeof AuthenticatedSelectSchoolRoute
  '/_authenticated/sis-export': typeof AuthenticatedSisExportRoute
  '/_authenticated/academic/calendar': typeof AuthenticatedAcademicCalendarRoute
  '/_authenticated/academic/classrooms': typeof AuthenticatedAcademicClassroomsRoute
  '/_authenticated/academic/curricula': typeof AuthenticatedAcademicCurriculaRoute
  '/_authenticated/academic/grade-levels': typeof AuthenticatedAcademicGradeLevelsRoute
  '/_authenticated/academic/subjects': typeof AuthenticatedAcademicSubjectsRoute
  '/_authenticated/academic/terms': typeof AuthenticatedAcademicTermsRoute
  '/_authenticated/academic/years': typeof AuthenticatedAcademicYearsRoute
  '/_authenticated/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/_authenticated/guardians/$guardianId': typeof AuthenticatedGuardiansGuardianIdRoute
  '/_authenticated/permission-requests/$requestId': typeof AuthenticatedPermissionRequestsRequestIdRouteWithChildren
  '/_authenticated/permission-requests/new': typeof AuthenticatedPermissionRequestsNewRoute
  '/_authenticated/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/_authenticated/portal/permission-requests': typeof AuthenticatedPortalPermissionRequestsRouteWithChildren
  '/_authenticated/portal/report-cards': typeof AuthenticatedPortalReportCardsRoute
  '/_authenticated/portal/schedule': typeof AuthenticatedPortalScheduleRoute
  '/_authenticated/portal/scores': typeof AuthenticatedPortalScoresRoute
  '/_authenticated/report-cards/$id': typeof AuthenticatedReportCardsIdRoute
  '/_authenticated/schedule/my': typeof AuthenticatedScheduleMyRoute
  '/_authenticated/sis-imports/$jobId': typeof AuthenticatedSisImportsJobIdRoute
  '/_authenticated/sis-imports/new': typeof AuthenticatedSisImportsNewRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/_authenticated/student/report-cards': typeof AuthenticatedStudentReportCardsRoute
  '/_authenticated/student/schedule': typeof AuthenticatedStudentScheduleRoute
  '/_authenticated/student/scores': typeof AuthenticatedStudentScoresRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/guardians/': typeof AuthenticatedGuardiansIndexRoute
  '/_authenticated/permission-requests/': typeof AuthenticatedPermissionRequestsIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/report-cards/': typeof AuthenticatedReportCardsIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/_authenticated/sis-imports/': typeof AuthenticatedSisImportsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teaching-assignments/': typeof AuthenticatedTeachingAssignmentsIndexRoute
  '/_authenticated/attendance/session/$id': typeof AuthenticatedAttendanceSessionIdRoute
  '/_authenticated/permission-requests/$requestId/edit': typeof AuthenticatedPermissionRequestsRequestIdEditRoute
  '/_authenticated/portal/permission-requests/$requestId': typeof AuthenticatedPortalPermissionRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/access-pending'
    | '/dashboard'
    | '/notifications'
    | '/select-organization'
    | '/select-school'
    | '/sis-export'
    | '/academic/calendar'
    | '/academic/classrooms'
    | '/academic/curricula'
    | '/academic/grade-levels'
    | '/academic/subjects'
    | '/academic/terms'
    | '/academic/years'
    | '/assessments/$id'
    | '/guardians/$guardianId'
    | '/permission-requests/$requestId'
    | '/permission-requests/new'
    | '/portal/attendance'
    | '/portal/permission-requests'
    | '/portal/report-cards'
    | '/portal/schedule'
    | '/portal/scores'
    | '/report-cards/$id'
    | '/schedule/my'
    | '/sis-imports/$jobId'
    | '/sis-imports/new'
    | '/staff/$staffId'
    | '/student/attendance'
    | '/student/report-cards'
    | '/student/schedule'
    | '/student/scores'
    | '/students/$studentId'
    | '/assessments/'
    | '/attendance/'
    | '/guardians/'
    | '/permission-requests/'
    | '/portal/'
    | '/report-cards/'
    | '/schedule/'
    | '/sis-imports/'
    | '/staff/'
    | '/student/'
    | '/students/'
    | '/teaching-assignments/'
    | '/attendance/session/$id'
    | '/permission-requests/$requestId/edit'
    | '/portal/permission-requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/access-pending'
    | '/dashboard'
    | '/notifications'
    | '/select-organization'
    | '/select-school'
    | '/sis-export'
    | '/academic/calendar'
    | '/academic/classrooms'
    | '/academic/curricula'
    | '/academic/grade-levels'
    | '/academic/subjects'
    | '/academic/terms'
    | '/academic/years'
    | '/assessments/$id'
    | '/guardians/$guardianId'
    | '/permission-requests/$requestId'
    | '/permission-requests/new'
    | '/portal/attendance'
    | '/portal/permission-requests'
    | '/portal/report-cards'
    | '/portal/schedule'
    | '/portal/scores'
    | '/report-cards/$id'
    | '/schedule/my'
    | '/sis-imports/$jobId'
    | '/sis-imports/new'
    | '/staff/$staffId'
    | '/student/attendance'
    | '/student/report-cards'
    | '/student/schedule'
    | '/student/scores'
    | '/students/$studentId'
    | '/assessments'
    | '/attendance'
    | '/guardians'
    | '/permission-requests'
    | '/portal'
    | '/report-cards'
    | '/schedule'
    | '/sis-imports'
    | '/staff'
    | '/student'
    | '/students'
    | '/teaching-assignments'
    | '/attendance/session/$id'
    | '/permission-requests/$requestId/edit'
    | '/portal/permission-requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/healthz'
    | '/reset-password'
    | '/_authenticated/access-pending'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/select-organization'
    | '/_authenticated/select-school'
    | '/_authenticated/sis-export'
    | '/_authenticated/academic/calendar'
    | '/_authenticated/academic/classrooms'
    | '/_authenticated/academic/curricula'
    | '/_authenticated/academic/grade-levels'
    | '/_authenticated/academic/subjects'
    | '/_authenticated/academic/terms'
    | '/_authenticated/academic/years'
    | '/_authenticated/assessments/$id'
    | '/_authenticated/guardians/$guardianId'
    | '/_authenticated/permission-requests/$requestId'
    | '/_authenticated/permission-requests/new'
    | '/_authenticated/portal/attendance'
    | '/_authenticated/portal/permission-requests'
    | '/_authenticated/portal/report-cards'
    | '/_authenticated/portal/schedule'
    | '/_authenticated/portal/scores'
    | '/_authenticated/report-cards/$id'
    | '/_authenticated/schedule/my'
    | '/_authenticated/sis-imports/$jobId'
    | '/_authenticated/sis-imports/new'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/student/attendance'
    | '/_authenticated/student/report-cards'
    | '/_authenticated/student/schedule'
    | '/_authenticated/student/scores'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/assessments/'
    | '/_authenticated/attendance/'
    | '/_authenticated/guardians/'
    | '/_authenticated/permission-requests/'
    | '/_authenticated/portal/'
    | '/_authenticated/report-cards/'
    | '/_authenticated/schedule/'
    | '/_authenticated/sis-imports/'
    | '/_authenticated/staff/'
    | '/_authenticated/student/'
    | '/_authenticated/students/'
    | '/_authenticated/teaching-assignments/'
    | '/_authenticated/attendance/session/$id'
    | '/_authenticated/permission-requests/$requestId/edit'
    | '/_authenticated/portal/permission-requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthzRoute: typeof HealthzRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-pending': {
      id: '/_authenticated/access-pending'
      path: '/access-pending'
      fullPath: '/access-pending'
      preLoaderRoute: typeof AuthenticatedAccessPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-organization': {
      id: '/_authenticated/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof AuthenticatedSelectOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/select-school': {
      id: '/_authenticated/select-school'
      path: '/select-school'
      fullPath: '/select-school'
      preLoaderRoute: typeof AuthenticatedSelectSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sis-export': {
      id: '/_authenticated/sis-export'
      path: '/sis-export'
      fullPath: '/sis-export'
      preLoaderRoute: typeof AuthenticatedSisExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/calendar': {
      id: '/_authenticated/academic/calendar'
      path: '/academic/calendar'
      fullPath: '/academic/calendar'
      preLoaderRoute: typeof AuthenticatedAcademicCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/classrooms': {
      id: '/_authenticated/academic/classrooms'
      path: '/academic/classrooms'
      fullPath: '/academic/classrooms'
      preLoaderRoute: typeof AuthenticatedAcademicClassroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/curricula': {
      id: '/_authenticated/academic/curricula'
      path: '/academic/curricula'
      fullPath: '/academic/curricula'
      preLoaderRoute: typeof AuthenticatedAcademicCurriculaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/grade-levels': {
      id: '/_authenticated/academic/grade-levels'
      path: '/academic/grade-levels'
      fullPath: '/academic/grade-levels'
      preLoaderRoute: typeof AuthenticatedAcademicGradeLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/subjects': {
      id: '/_authenticated/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/academic/subjects'
      preLoaderRoute: typeof AuthenticatedAcademicSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/terms': {
      id: '/_authenticated/academic/terms'
      path: '/academic/terms'
      fullPath: '/academic/terms'
      preLoaderRoute: typeof AuthenticatedAcademicTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic/years': {
      id: '/_authenticated/academic/years'
      path: '/academic/years'
      fullPath: '/academic/years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$id': {
      id: '/_authenticated/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians/': {
      id: '/_authenticated/guardians/'
      path: '/guardians'
      fullPath: '/guardians/'
      preLoaderRoute: typeof AuthenticatedGuardiansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardians/$guardianId': {
      id: '/_authenticated/guardians/$guardianId'
      path: '/guardians/$guardianId'
      fullPath: '/guardians/$guardianId'
      preLoaderRoute: typeof AuthenticatedGuardiansGuardianIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permission-requests/': {
      id: '/_authenticated/permission-requests/'
      path: '/permission-requests'
      fullPath: '/permission-requests/'
      preLoaderRoute: typeof AuthenticatedPermissionRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permission-requests/$requestId': {
      id: '/_authenticated/permission-requests/$requestId'
      path: '/permission-requests/$requestId'
      fullPath: '/permission-requests/$requestId'
      preLoaderRoute: typeof AuthenticatedPermissionRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permission-requests/new': {
      id: '/_authenticated/permission-requests/new'
      path: '/permission-requests/new'
      fullPath: '/permission-requests/new'
      preLoaderRoute: typeof AuthenticatedPermissionRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/attendance': {
      id: '/_authenticated/portal/attendance'
      path: '/portal/attendance'
      fullPath: '/portal/attendance'
      preLoaderRoute: typeof AuthenticatedPortalAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/permission-requests': {
      id: '/_authenticated/portal/permission-requests'
      path: '/portal/permission-requests'
      fullPath: '/portal/permission-requests'
      preLoaderRoute: typeof AuthenticatedPortalPermissionRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/report-cards': {
      id: '/_authenticated/portal/report-cards'
      path: '/portal/report-cards'
      fullPath: '/portal/report-cards'
      preLoaderRoute: typeof AuthenticatedPortalReportCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/schedule': {
      id: '/_authenticated/portal/schedule'
      path: '/portal/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof AuthenticatedPortalScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/scores': {
      id: '/_authenticated/portal/scores'
      path: '/portal/scores'
      fullPath: '/portal/scores'
      preLoaderRoute: typeof AuthenticatedPortalScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-cards/': {
      id: '/_authenticated/report-cards/'
      path: '/report-cards'
      fullPath: '/report-cards/'
      preLoaderRoute: typeof AuthenticatedReportCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-cards/$id': {
      id: '/_authenticated/report-cards/$id'
      path: '/report-cards/$id'
      fullPath: '/report-cards/$id'
      preLoaderRoute: typeof AuthenticatedReportCardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule/my': {
      id: '/_authenticated/schedule/my'
      path: '/schedule/my'
      fullPath: '/schedule/my'
      preLoaderRoute: typeof AuthenticatedScheduleMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sis-imports/': {
      id: '/_authenticated/sis-imports/'
      path: '/sis-imports'
      fullPath: '/sis-imports/'
      preLoaderRoute: typeof AuthenticatedSisImportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sis-imports/$jobId': {
      id: '/_authenticated/sis-imports/$jobId'
      path: '/sis-imports/$jobId'
      fullPath: '/sis-imports/$jobId'
      preLoaderRoute: typeof AuthenticatedSisImportsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sis-imports/new': {
      id: '/_authenticated/sis-imports/new'
      path: '/sis-imports/new'
      fullPath: '/sis-imports/new'
      preLoaderRoute: typeof AuthenticatedSisImportsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/attendance': {
      id: '/_authenticated/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof AuthenticatedStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/report-cards': {
      id: '/_authenticated/student/report-cards'
      path: '/student/report-cards'
      fullPath: '/student/report-cards'
      preLoaderRoute: typeof AuthenticatedStudentReportCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/schedule': {
      id: '/_authenticated/student/schedule'
      path: '/student/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof AuthenticatedStudentScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/scores': {
      id: '/_authenticated/student/scores'
      path: '/student/scores'
      fullPath: '/student/scores'
      preLoaderRoute: typeof AuthenticatedStudentScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teaching-assignments/': {
      id: '/_authenticated/teaching-assignments/'
      path: '/teaching-assignments'
      fullPath: '/teaching-assignments/'
      preLoaderRoute: typeof AuthenticatedTeachingAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/session/$id': {
      id: '/_authenticated/attendance/session/$id'
      path: '/attendance/session/$id'
      fullPath: '/attendance/session/$id'
      preLoaderRoute: typeof AuthenticatedAttendanceSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permission-requests/$requestId/edit': {
      id: '/_authenticated/permission-requests/$requestId/edit'
      path: '/edit'
      fullPath: '/permission-requests/$requestId/edit'
      preLoaderRoute: typeof AuthenticatedPermissionRequestsRequestIdEditRouteImport
      parentRoute: typeof AuthenticatedPermissionRequestsRequestIdRoute
    }
    '/_authenticated/portal/permission-requests/$requestId': {
      id: '/_authenticated/portal/permission-requests/$requestId'
      path: '/$requestId'
      fullPath: '/portal/permission-requests/$requestId'
      preLoaderRoute: typeof AuthenticatedPortalPermissionRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedPortalPermissionRequestsRoute
    }
  }
}

interface AuthenticatedPermissionRequestsRequestIdRouteChildren {
  AuthenticatedPermissionRequestsRequestIdEditRoute: typeof AuthenticatedPermissionRequestsRequestIdEditRoute
}

const AuthenticatedPermissionRequestsRequestIdRouteChildren: AuthenticatedPermissionRequestsRequestIdRouteChildren =
  {
    AuthenticatedPermissionRequestsRequestIdEditRoute:
      AuthenticatedPermissionRequestsRequestIdEditRoute,
  }

const AuthenticatedPermissionRequestsRequestIdRouteWithChildren =
  AuthenticatedPermissionRequestsRequestIdRoute._addFileChildren(
    AuthenticatedPermissionRequestsRequestIdRouteChildren,
  )

interface AuthenticatedPortalPermissionRequestsRouteChildren {
  AuthenticatedPortalPermissionRequestsRequestIdRoute: typeof AuthenticatedPortalPermissionRequestsRequestIdRoute
}

const AuthenticatedPortalPermissionRequestsRouteChildren: AuthenticatedPortalPermissionRequestsRouteChildren =
  {
    AuthenticatedPortalPermissionRequestsRequestIdRoute:
      AuthenticatedPortalPermissionRequestsRequestIdRoute,
  }

const AuthenticatedPortalPermissionRequestsRouteWithChildren =
  AuthenticatedPortalPermissionRequestsRoute._addFileChildren(
    AuthenticatedPortalPermissionRequestsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessPendingRoute: typeof AuthenticatedAccessPendingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSelectOrganizationRoute: typeof AuthenticatedSelectOrganizationRoute
  AuthenticatedSelectSchoolRoute: typeof AuthenticatedSelectSchoolRoute
  AuthenticatedSisExportRoute: typeof AuthenticatedSisExportRoute
  AuthenticatedAcademicCalendarRoute: typeof AuthenticatedAcademicCalendarRoute
  AuthenticatedAcademicClassroomsRoute: typeof AuthenticatedAcademicClassroomsRoute
  AuthenticatedAcademicCurriculaRoute: typeof AuthenticatedAcademicCurriculaRoute
  AuthenticatedAcademicGradeLevelsRoute: typeof AuthenticatedAcademicGradeLevelsRoute
  AuthenticatedAcademicSubjectsRoute: typeof AuthenticatedAcademicSubjectsRoute
  AuthenticatedAcademicTermsRoute: typeof AuthenticatedAcademicTermsRoute
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRoute
  AuthenticatedAssessmentsIdRoute: typeof AuthenticatedAssessmentsIdRoute
  AuthenticatedGuardiansGuardianIdRoute: typeof AuthenticatedGuardiansGuardianIdRoute
  AuthenticatedPermissionRequestsRequestIdRoute: typeof AuthenticatedPermissionRequestsRequestIdRouteWithChildren
  AuthenticatedPermissionRequestsNewRoute: typeof AuthenticatedPermissionRequestsNewRoute
  AuthenticatedPortalAttendanceRoute: typeof AuthenticatedPortalAttendanceRoute
  AuthenticatedPortalPermissionRequestsRoute: typeof AuthenticatedPortalPermissionRequestsRouteWithChildren
  AuthenticatedPortalReportCardsRoute: typeof AuthenticatedPortalReportCardsRoute
  AuthenticatedPortalScheduleRoute: typeof AuthenticatedPortalScheduleRoute
  AuthenticatedPortalScoresRoute: typeof AuthenticatedPortalScoresRoute
  AuthenticatedReportCardsIdRoute: typeof AuthenticatedReportCardsIdRoute
  AuthenticatedScheduleMyRoute: typeof AuthenticatedScheduleMyRoute
  AuthenticatedSisImportsJobIdRoute: typeof AuthenticatedSisImportsJobIdRoute
  AuthenticatedSisImportsNewRoute: typeof AuthenticatedSisImportsNewRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedStudentAttendanceRoute: typeof AuthenticatedStudentAttendanceRoute
  AuthenticatedStudentReportCardsRoute: typeof AuthenticatedStudentReportCardsRoute
  AuthenticatedStudentScheduleRoute: typeof AuthenticatedStudentScheduleRoute
  AuthenticatedStudentScoresRoute: typeof AuthenticatedStudentScoresRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedGuardiansIndexRoute: typeof AuthenticatedGuardiansIndexRoute
  AuthenticatedPermissionRequestsIndexRoute: typeof AuthenticatedPermissionRequestsIndexRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedReportCardsIndexRoute: typeof AuthenticatedReportCardsIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
  AuthenticatedSisImportsIndexRoute: typeof AuthenticatedSisImportsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachingAssignmentsIndexRoute: typeof AuthenticatedTeachingAssignmentsIndexRoute
  AuthenticatedAttendanceSessionIdRoute: typeof AuthenticatedAttendanceSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessPendingRoute: AuthenticatedAccessPendingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSelectOrganizationRoute: AuthenticatedSelectOrganizationRoute,
  AuthenticatedSelectSchoolRoute: AuthenticatedSelectSchoolRoute,
  AuthenticatedSisExportRoute: AuthenticatedSisExportRoute,
  AuthenticatedAcademicCalendarRoute: AuthenticatedAcademicCalendarRoute,
  AuthenticatedAcademicClassroomsRoute: AuthenticatedAcademicClassroomsRoute,
  AuthenticatedAcademicCurriculaRoute: AuthenticatedAcademicCurriculaRoute,
  AuthenticatedAcademicGradeLevelsRoute: AuthenticatedAcademicGradeLevelsRoute,
  AuthenticatedAcademicSubjectsRoute: AuthenticatedAcademicSubjectsRoute,
  AuthenticatedAcademicTermsRoute: AuthenticatedAcademicTermsRoute,
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRoute,
  AuthenticatedAssessmentsIdRoute: AuthenticatedAssessmentsIdRoute,
  AuthenticatedGuardiansGuardianIdRoute: AuthenticatedGuardiansGuardianIdRoute,
  AuthenticatedPermissionRequestsRequestIdRoute:
    AuthenticatedPermissionRequestsRequestIdRouteWithChildren,
  AuthenticatedPermissionRequestsNewRoute:
    AuthenticatedPermissionRequestsNewRoute,
  AuthenticatedPortalAttendanceRoute: AuthenticatedPortalAttendanceRoute,
  AuthenticatedPortalPermissionRequestsRoute:
    AuthenticatedPortalPermissionRequestsRouteWithChildren,
  AuthenticatedPortalReportCardsRoute: AuthenticatedPortalReportCardsRoute,
  AuthenticatedPortalScheduleRoute: AuthenticatedPortalScheduleRoute,
  AuthenticatedPortalScoresRoute: AuthenticatedPortalScoresRoute,
  AuthenticatedReportCardsIdRoute: AuthenticatedReportCardsIdRoute,
  AuthenticatedScheduleMyRoute: AuthenticatedScheduleMyRoute,
  AuthenticatedSisImportsJobIdRoute: AuthenticatedSisImportsJobIdRoute,
  AuthenticatedSisImportsNewRoute: AuthenticatedSisImportsNewRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
  AuthenticatedStudentAttendanceRoute: AuthenticatedStudentAttendanceRoute,
  AuthenticatedStudentReportCardsRoute: AuthenticatedStudentReportCardsRoute,
  AuthenticatedStudentScheduleRoute: AuthenticatedStudentScheduleRoute,
  AuthenticatedStudentScoresRoute: AuthenticatedStudentScoresRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedGuardiansIndexRoute: AuthenticatedGuardiansIndexRoute,
  AuthenticatedPermissionRequestsIndexRoute:
    AuthenticatedPermissionRequestsIndexRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedReportCardsIndexRoute: AuthenticatedReportCardsIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
  AuthenticatedSisImportsIndexRoute: AuthenticatedSisImportsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachingAssignmentsIndexRoute:
    AuthenticatedTeachingAssignmentsIndexRoute,
  AuthenticatedAttendanceSessionIdRoute: AuthenticatedAttendanceSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthzRoute: HealthzRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
